//! `Z_HUFFMAN_ONLY` deflate strategy — Huffman-only, no string matching.
//!
//! This module ports the C function `deflate_huff()` from upstream zlib
//! `deflate.c` (lines 2155-2185). It implements the simplest of zlib's five
//! block-compression strategies: **no LZ77 string matching is performed at
//! all**. Every input byte is emitted as a *literal*, and all compression
//! comes from the entropy (Huffman) stage applied when the block is flushed.
//!
//! The strategy is selected when the stream's strategy is `Strategy::HuffmanOnly`
//! (C `Z_HUFFMAN_ONLY`) and is dispatched from the per-level strategy table in
//! `crate::deflate::strategy`.
//!
//! # Relationship to the other strategies
//!
//! Unlike the `deflate_fast` and `deflate_slow` strategies, this function never
//! consults the hash table, never calls `longest_match`, and never inserts
//! strings into the dictionary. Consequently it leaves `insert` at `0` and sets
//! `match_length = 0` on every iteration so that the trees layer always tallies
//! a literal (never a match). Because no match state is maintained, switching
//! the stream to or away from `Z_HUFFMAN_ONLY` mid-stream is safe: the hash
//! table is simply regenerated by the next non-Huffman run, exactly as in the C
//! implementation.
//!
//! # Byte-exactness (AAP §0.6.7, §0.7.1)
//!
//! Output is byte-identical to canonical C zlib for the same input because:
//!
//! * every byte is tallied via [`trees::tr_tally_lit`] in input order, and
//! * the block-flush decisions (`tr_tally_lit` returning `true`, the `Z_FINISH`
//!   tail, and the trailing `sym_next != 0` flush) mirror the C control flow
//!   exactly.
//!
//! # Safety
//!
//! This module contains **no `unsafe`** (AAP §0.6.2) and is `no_std`-clean: it
//! references only crate-internal types and performs only checked slice
//! indexing.

use crate::constants::FlushMode;
use crate::deflate::flush_block;
use crate::deflate::state::{BlockState, DeflateStream};
use crate::deflate::trees;

/// Compress the current input using the `Z_HUFFMAN_ONLY` strategy.
///
/// Ports C `deflate_huff()` (`deflate.c` L2155-2185). Emits every available
/// input byte as a Huffman literal — performing no string matching — and
/// flushes blocks exactly when the C implementation does.
///
/// # Parameters
///
/// * `s` — the per-call deflate stream (the borrowed engine state plus the
///   input and output cursors).
/// * `flush` — the caller's requested [`FlushMode`]. Only `NoFlush` (keep the
///   block open and ask for more data) and `Finish` (close the final block)
///   change control flow here, matching C; all other modes behave like the
///   non-finishing path.
///
/// # Returns
///
/// A [`BlockState`] telling the `deflate()` driver how far the block got:
///
/// * [`BlockState::NeedMore`] — ran out of input before completing the block
///   while `flush == NoFlush`, or a non-final flush filled the output buffer.
/// * [`BlockState::FinishDone`] — the final block was fully emitted for
///   `Z_FINISH`.
/// * [`BlockState::FinishStarted`] — `Z_FINISH` was requested but the output
///   buffer filled while flushing the final block (propagated from
///   [`flush_block`]).
/// * [`BlockState::BlockDone`] — a (non-final) block flush completed.
pub(crate) fn deflate_huff(s: &mut DeflateStream, flush: FlushMode) -> BlockState {
    loop {
        // Make sure that we have a literal to write. A single byte of lookahead
        // is sufficient for this strategy, so we refill only when the window is
        // completely drained (C tests `s->lookahead == 0`, *not*
        // `< MIN_LOOKAHEAD`).
        if s.state.lookahead == 0 {
            s.fill_window();
            if s.state.lookahead == 0 {
                // No more input is currently available.
                if flush == FlushMode::NoFlush {
                    // The caller may still supply more data on a later call.
                    return BlockState::NeedMore;
                }
                // A flush was requested: stop reading and emit the open block.
                break;
            }
        }

        // Output a literal byte. Setting `match_length = 0` marks this symbol as
        // a literal (never a match), which also guarantees that nothing is
        // inserted into the hash table for this strategy.
        s.state.match_length = 0;
        let lc = s.state.window[s.state.strstart];
        let bflush = trees::tr_tally_lit(s.state, lc);
        s.state.lookahead -= 1;
        s.state.strstart += 1;

        // If the symbol buffer filled up, flush the current (non-final) block.
        // A filled output buffer aborts early with `BlockState::NeedMore`.
        if bflush && let Some(bs) = flush_block(s, false) {
            return bs;
        }
    }

    // No string matching is ever performed, so nothing is pending insertion
    // into the dictionary for a future call.
    s.state.insert = 0;

    if flush == FlushMode::Finish {
        // Emit the final block. If the output buffer fills mid-flush,
        // `flush_block` yields `Some(BlockState::FinishStarted)`; otherwise
        // finishing is complete.
        if let Some(bs) = flush_block(s, true) {
            return bs;
        }
        return BlockState::FinishDone;
    }

    // Not finishing: if any symbols remain buffered, flush a non-final block.
    if s.state.sym_next != 0
        && let Some(bs) = flush_block(s, false)
    {
        return bs;
    }

    BlockState::BlockDone
}
