// Copyright (C) 1995-2026 Jean-loup Gailly and Mark Adler
// Rust translation: zlib-rs crate
// SPDX-License-Identifier: Zlib
//
// Run-length encoding compression strategy (Z_RLE).
// Port of C `deflate_rle` from deflate.c lines 2079–2149.

#![allow(dead_code)]

//! Run-length encoding (RLE) compression strategy for the DEFLATE engine.
//!
//! This module implements `deflate_rle`, one of five compression strategy
//! functions dispatched by the main `deflate()` loop. It is selected when
//! the caller specifies `Z_RLE` (strategy 3) via `deflateInit2` or
//! `deflateParams`.
//!
//! # Algorithm Overview
//!
//! Unlike the general LZ77 strategies (`deflate_fast`, `deflate_slow`),
//! `deflate_rle` only searches for runs of identical bytes at distance 1.
//! It does **not** maintain a hash table — hash chains are unused and the
//! `insert` counter is zeroed on exit. If the strategy is later changed
//! away from Z_RLE via `deflateParams`, the hash table will be
//! regenerated by the new strategy.
//!
//! # Wire-Format Compatibility
//!
//! The output is a valid DEFLATE stream (RFC 1951). Matches always have
//! distance = 1, so only the lowest distance code (code 0, extra bits = 0)
//! is used. This produces highly compressible output for data with many
//! repeated bytes, at the cost of very poor compression for non-repetitive
//! data.
//!
//! # C Source Reference
//!
//! - **Function:** `deflate_rle` in `deflate.c` lines 2084–2149
//! - **Called by:** Main `deflate()` loop when `state.strategy == Z_RLE`
//! - **Calls:** `fill_window`, `tally_dist`, `tally_lit`, `tr_flush_block`

// In no_std mode, pull alloc types that the std prelude normally provides.
#[cfg(not(feature = "std"))]
use alloc::vec::Vec;

use crate::constants::{MAX_MATCH, MIN_MATCH, Z_FINISH, Z_NO_FLUSH};
use crate::deflate::state::{BlockState, DeflateState};
use crate::deflate::trees::{tally_dist, tally_lit, tr_flush_block};
use crate::stream::ZStream;

// ===========================================================================
// Local helpers
// ===========================================================================

/// Fill the sliding window with data from the input stream.
///
/// Delegates to the real `fill_window` in the parent `deflate` module.
///
/// # Safety
///
/// `strm` must be a valid pointer to the `ZStream` that owns this
/// `DeflateState`. The pointer is valid for the lifetime of the
/// `deflate()` call.
#[inline(always)]
unsafe fn do_fill_window(state: &mut DeflateState, strm: *mut ZStream) {
    // SAFETY: strm is the raw pointer to the parent ZStream passed from
    // deflate(). fill_window only reads/writes strm fields (avail_in,
    // next_in, total_in, adler) that do not overlap with DeflateState.
    super::fill_window(state, unsafe { &mut *strm });
}

/// Flush the current block to the pending output buffer.
///
/// This local helper corresponds to the C `FLUSH_BLOCK_ONLY` macro
/// (deflate.c lines 1630–1639). It:
///
/// 1. Computes the block data slice from `window[block_start..strstart]`
///    (or `None` if `block_start` is negative, indicating no valid window
///    data for a stored block fallback).
/// 2. Calls [`tr_flush_block`] to select the optimal block encoding
///    (stored, static Huffman, or dynamic Huffman) and write the
///    compressed block into the pending buffer.
/// 3. Advances `block_start` to `strstart`, marking the start of the
///    next block.
///
/// The C `FLUSH_BLOCK` macro additionally checks `avail_out` and may
/// return `NeedMore`/`FinishStarted`. That output-buffer check is
/// handled by the main `deflate()` loop after the strategy function
/// returns, not within the strategy function itself.
fn flush_block(state: &mut DeflateState, last: bool) {
    let stored_len = (state.strstart as i64 - state.block_start) as u64;

    // We need to pass a slice of the window to tr_flush_block, but
    // tr_flush_block also takes &mut DeflateState. To satisfy the
    // borrow checker, we copy the block data to a temporary buffer.
    // This copy only matters for stored-block selection (level 0 or
    // when stored is cheaper); for the common case of Huffman-coded
    // blocks, the buffer is not accessed.
    if state.block_start >= 0 {
        let start = state.block_start as usize;
        let end = state.strstart;
        let buf: Vec<u8> = state.window[start..end].to_vec();
        tr_flush_block(state, Some(&buf), stored_len, last);
    } else {
        tr_flush_block(state, None, stored_len, last);
    }

    state.block_start = state.strstart as i64;
}

// ===========================================================================
// Public API
// ===========================================================================

/// Run-length encoding compression (Z_RLE strategy).
///
/// Simply looks for runs of bytes, generating matches only of distance one.
/// Does not maintain a hash table. (It will be regenerated if this run of
/// deflate switches away from Z_RLE.)
///
/// # Algorithm
///
/// For each position in the input:
///
/// 1. Check if the byte at `window[strstart]` equals the byte at
///    `window[strstart - 1]` (distance 1). If so, scan forward to
///    measure the run length (up to [`MAX_MATCH`] = 258 bytes).
/// 2. If the run length ≥ [`MIN_MATCH`] (3), emit a distance/length
///    pair via [`tally_dist`] with distance = 1.
/// 3. Otherwise, emit a literal byte via [`tally_lit`].
/// 4. When the symbol buffer is full (tally returns `true`), flush
///    the current block.
///
/// # Parameters
///
/// - `state`: Mutable reference to the deflate compression state. The
///   function reads from and writes to `window`, `strstart`, `lookahead`,
///   `match_length`, `sym_next`, `insert`, and `block_start`.
/// - `flush`: Flush mode from the caller. `Z_NO_FLUSH` allows the
///   function to return early when more input is needed. `Z_FINISH`
///   causes the final block to be emitted after the loop.
///
/// # Returns
///
/// - [`BlockState::NeedMore`] — Lookahead is insufficient and
///   `flush == Z_NO_FLUSH`; the caller should provide more input.
/// - [`BlockState::BlockDone`] — A non-final block was flushed.
/// - [`BlockState::FinishDone`] — The final block was emitted
///   (`flush == Z_FINISH`).
///
/// # C Source
///
/// Direct port of `deflate_rle` in `deflate.c:2084–2149`.
pub(crate) fn deflate_rle(state: &mut DeflateState, strm: *mut ZStream, flush: i32) -> BlockState {
    loop {
        // ------------------------------------------------------------------
        // Ensure sufficient lookahead.
        //
        // The RLE strategy needs up to MAX_MATCH (258) bytes of lookahead
        // for the longest possible run, plus one extra byte for the
        // unrolled initial comparison. Unlike the general strategies that
        // use MIN_LOOKAHEAD (262), RLE uses MAX_MATCH as its threshold
        // because it does not need the extra bytes for hash insertion.
        // ------------------------------------------------------------------
        if state.lookahead <= MAX_MATCH {
            // SAFETY: strm is valid for the duration of deflate().
            unsafe {
                do_fill_window(state, strm);
            }

            if state.lookahead <= MAX_MATCH && flush == Z_NO_FLUSH {
                return BlockState::NeedMore;
            }

            if state.lookahead == 0 {
                break; // Flush the current block
            }
        }

        // ------------------------------------------------------------------
        // Detect runs: see how many times the previous byte repeats.
        //
        // We look at window[strstart - 1] (the "previous" byte) and check
        // how many consecutive bytes starting at window[strstart] are
        // identical to it. A match at distance 1 with length >= MIN_MATCH
        // is emitted as a distance/length pair.
        //
        // The guard `strstart > 0` ensures we don't read before the
        // window start. At position 0, there is no "previous byte" to
        // match against, so only a literal can be emitted.
        // ------------------------------------------------------------------
        state.match_length = 0;

        if state.lookahead >= MIN_MATCH && state.strstart > 0 {
            // Byte at distance 1 from current position
            let prev = state.window[state.strstart - 1];

            // Quick check: first 3 bytes must match (minimum match length)
            if prev == state.window[state.strstart]
                && prev == state.window[state.strstart + 1]
                && prev == state.window[state.strstart + 2]
            {
                // At least MIN_MATCH bytes match. Scan forward to find the
                // full run length. The end boundary is strstart + MAX_MATCH,
                // clamped to the window size for safety.
                let scan_end = (state.strstart + MAX_MATCH).min(state.window.len());
                let mut pos = state.strstart + 3; // Already verified 3 bytes

                while pos < scan_end && state.window[pos] == prev {
                    pos += 1;
                }

                // Run length is the number of matching bytes from strstart
                state.match_length = pos - state.strstart;

                // Clamp to available lookahead
                if state.match_length > state.lookahead {
                    state.match_length = state.lookahead;
                }
            }
        }

        // ------------------------------------------------------------------
        // Emit match (distance 1) or literal
        // ------------------------------------------------------------------
        let bflush = if state.match_length >= MIN_MATCH {
            // Emit a distance/length pair. Distance is always 1 (RLE).
            // Length is encoded as (match_length - MIN_MATCH) per DEFLATE.
            let len = (state.match_length - MIN_MATCH) as u32;
            let result = tally_dist(state, 1, len);

            state.lookahead -= state.match_length;
            state.strstart += state.match_length;
            state.match_length = 0;

            result
        } else {
            // No run detected (or run too short). Emit a literal byte.
            let c = state.window[state.strstart];
            let result = tally_lit(state, c);

            state.lookahead -= 1;
            state.strstart += 1;

            result
        };

        // If the symbol buffer is full, flush the current block.
        if bflush {
            flush_block(state, false);
        }
    }

    // ------------------------------------------------------------------
    // Post-loop: finalize the block
    //
    // Set insert = 0 because the RLE strategy does not maintain the hash
    // table. If deflateParams later switches to a hash-based strategy,
    // the hash table will be rebuilt from scratch.
    // ------------------------------------------------------------------
    state.insert = 0;

    if flush == Z_FINISH {
        // Emit the final block (last = true).
        flush_block(state, true);
        return BlockState::FinishDone;
    }

    // If there are any pending symbols, flush a non-final block.
    if state.sym_next > 0 {
        flush_block(state, false);
    }

    BlockState::BlockDone
}

// ===========================================================================
// Unit tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::stream::ZStream;

    fn dummy_strm() -> ZStream {
        ZStream::new()
    }

    /// Helper: create a minimal `DeflateState` for testing the RLE
    /// algorithm. Sets up a small window with controlled data and
    /// configures the state so that the compression loop can run
    /// without needing the full deflate infrastructure.
    fn make_test_state(window_data: &[u8], strstart: usize, lookahead: usize) -> DeflateState {
        use crate::constants::Z_RLE;
        use crate::deflate::trees::tr_init;

        // Use minimal window/memory configuration
        let w_bits: usize = 9; // 512-byte window
        let mem_level: usize = 1;
        let level: usize = 1;
        let wrap: i32 = 0; // raw deflate

        let mut state = DeflateState::new(w_bits, mem_level, level, Z_RLE, wrap);

        // Initialize tree structures (descriptors, frequencies, block state).
        // This is essential — without tr_init, the tree flush operations
        // (build_tree/gen_bitlen) will panic on uninitialised descriptors.
        tr_init(&mut state);

        // Copy test data into the window
        let copy_len = window_data.len().min(state.window.len());
        state.window[..copy_len].copy_from_slice(&window_data[..copy_len]);

        // Set up the starting position and lookahead
        state.strstart = strstart;
        state.lookahead = lookahead;
        state.block_start = 0;
        state.window_size = state.window.len();
        state.match_length = 0;
        state.insert = 0;
        state.strategy = Z_RLE;

        state
    }

    #[test]
    fn test_rle_all_same_bytes() {
        // Window filled with all 'A' bytes. Starting at position 1
        // (so there's a "previous byte" at position 0), with enough
        // lookahead for a run.
        let data = vec![b'A'; 300];
        let mut state = make_test_state(&data, 1, 280);

        // Run with Z_FINISH to process all data
        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_FINISH);

        // The function should process data and return FinishDone
        assert_eq!(result, BlockState::FinishDone);

        // insert should be 0 (no hash table maintained)
        assert_eq!(state.insert, 0);

        // strstart should have advanced past all the data
        assert!(state.strstart > 1);
    }

    #[test]
    fn test_rle_no_runs() {
        // Window filled with alternating bytes (no runs of length >= 3)
        let mut data = vec![0u8; 300];
        for (i, b) in data.iter_mut().enumerate() {
            *b = (i % 2) as u8;
        }
        let mut state = make_test_state(&data, 1, 200);

        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_FINISH);

        assert_eq!(result, BlockState::FinishDone);
        assert_eq!(state.insert, 0);
    }

    #[test]
    fn test_rle_need_more_on_no_flush() {
        // With insufficient lookahead and Z_NO_FLUSH, should return NeedMore
        let data = vec![b'B'; 300];
        let mut state = make_test_state(&data, 1, 10); // Small lookahead <= MAX_MATCH

        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_NO_FLUSH);

        assert_eq!(result, BlockState::NeedMore);
    }

    #[test]
    fn test_rle_strstart_zero_edge_case() {
        // At strstart == 0, there is no previous byte, so only literals
        // should be emitted.
        let data = vec![b'C'; 300];
        let mut state = make_test_state(&data, 0, 100);

        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_FINISH);

        assert_eq!(result, BlockState::FinishDone);
        assert_eq!(state.insert, 0);
    }

    #[test]
    fn test_rle_mixed_runs_and_literals() {
        // Data with some runs and some non-repeating bytes
        let mut data = vec![0u8; 300];
        // Bytes 0-9: all 'A' (run of 10)
        for b in data.iter_mut().take(10) {
            *b = b'A';
        }
        // Bytes 10-14: different bytes (no run)
        data[10] = b'B';
        data[11] = b'C';
        data[12] = b'D';
        data[13] = b'E';
        data[14] = b'F';
        // Bytes 15-24: all 'X' (run of 10)
        for b in data.iter_mut().take(25).skip(15) {
            *b = b'X';
        }

        let mut state = make_test_state(&data, 1, 24);

        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_FINISH);

        assert_eq!(result, BlockState::FinishDone);
        assert_eq!(state.insert, 0);
    }

    #[test]
    fn test_rle_empty_lookahead_with_finish() {
        // Zero lookahead with Z_FINISH should emit final block and return
        let data = vec![0u8; 300];
        let mut state = make_test_state(&data, 100, 0);

        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_FINISH);

        assert_eq!(result, BlockState::FinishDone);
        assert_eq!(state.insert, 0);
    }

    #[test]
    fn test_rle_short_run_below_min_match() {
        // Run of exactly 2 bytes (below MIN_MATCH=3): should emit literals
        let mut data = vec![0u8; 300];
        data[0] = b'Z';
        data[1] = b'Z';
        data[2] = b'Z'; // 3 identical
        data[3] = b'Y'; // different

        let mut state = make_test_state(&data, 1, 10);

        // The run is exactly 3 bytes (MIN_MATCH), so should be emitted
        // as a match at distance 1.
        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_FINISH);

        assert_eq!(result, BlockState::FinishDone);
    }

    #[test]
    fn test_rle_match_length_clamped_to_lookahead() {
        // Long run but limited lookahead: match_length should be clamped
        let data = vec![b'Q'; 300];
        let mut state = make_test_state(&data, 1, 5); // Only 5 bytes of lookahead

        // With Z_FINISH and limited lookahead, the run will be clamped
        let result = deflate_rle(&mut state, &mut dummy_strm() as *mut ZStream, Z_FINISH);

        assert_eq!(result, BlockState::FinishDone);
        assert_eq!(state.insert, 0);
    }
}
