//! Cargo build script for the `zlib-rs` crate.
//!
//! This script runs once, on the host, *before* the crate itself is compiled.
//! It has two clearly separated responsibilities, mirroring the way upstream
//! C zlib bootstraps itself:
//!
//! 1. **CRC-32 table generation (Phase A).** Upstream zlib ships a 9 446-line
//!    pre-computed header, `crc32.h`, that is itself generated by `crc32.c`'s
//!    `make_crc_table()` routine. Rather than hand-porting that enormous table
//!    file, this build script *re-derives* the IEEE reflected CRC-32 lookup
//!    tables from the polynomial at build time and writes them to
//!    `${OUT_DIR}/crc32_table.rs`. The consuming module
//!    `src/checksum/crc32.rs` pulls them in with
//!    `include!(concat!(env!("OUT_DIR"), "/crc32_table.rs"));`. The generated
//!    values are **bit-identical** to upstream `crc32.h`, which is mandatory:
//!    the CRC-32 trailer is part of the gzip/zlib wire format, so any deviation
//!    would break stream compatibility with canonical zlib (AAP §0.6.5,
//!    §0.7.1).
//!
//! 2. **C-header emission (Phase B).** When header generation is requested
//!    (see Phase C), the script invokes `cbindgen` — configured by the
//!    repository-root `cbindgen.toml` — to regenerate a C header from the FFI
//!    surface in `src/ffi.rs`. This keeps the published C ABI in lock-step with
//!    the Rust source so the crate stays a drop-in replacement for `libz`
//!    (AAP §0.3.3, §0.6.2). Header generation is deliberately *best-effort*: it
//!    never aborts the crate build (the library does not depend on the header
//!    existing), degrading to a `cargo:warning` on any problem.
//!
//! The script is plain, dependency-light Rust. The only build-dependency it
//! uses is `cbindgen` (declared under `[build-dependencies]` in `Cargo.toml`);
//! the CRC table generation relies solely on the standard library and a handful
//! of integer operations, so it is fast, deterministic, and free of any
//! network or external-tool requirement.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

// ===========================================================================
// Phase A — CRC-32 table generation (port of `crc32.c` `make_crc_table()`)
// ===========================================================================

/// The IEEE 802.3 CRC-32 polynomial in *reflected* (LSB-first) bit order:
/// `x^32 + x^26 + x^23 + x^22 + x^16 + x^12 + x^11 + x^10 + x^8 + x^7 + x^5 +
/// x^4 + x^2 + x + 1`. This is the exact value `POLY` carries in `crc32.c`.
const POLY: u32 = 0xEDB8_8320;

/// Build the canonical byte-wise CRC-32 table (`crc_table[0]` in upstream
/// terminology): entry `n` is the CRC of the single byte `n`.
///
/// This is the faithful equivalent of the first loop of `make_crc_table()`:
/// for each of the 256 possible byte values, the register is reduced modulo
/// `POLY` eight times (once per bit). The first four entries are the well-known
/// zlib constants `0x00000000, 0x77073096, 0xEE0E612C, 0x990951BA`.
fn make_basic_table() -> [u32; 256] {
    let mut table = [0u32; 256];
    for (n, slot) in table.iter_mut().enumerate() {
        // `n` is in `0..256`, so the cast cannot truncate.
        let mut c = n as u32;
        for _ in 0..8 {
            c = if c & 1 != 0 { POLY ^ (c >> 1) } else { c >> 1 };
        }
        *slot = c;
    }
    table
}

/// Derive the "slice-by-8" acceleration tables from the basic table.
///
/// `tables[0]` is the basic byte-wise table; `tables[1..8]` let a consumer fold
/// eight input bytes per iteration. Each successive table is produced by
/// running one more byte-wise reduction step over the previous column value,
/// exactly as the well-known slice-by-N construction (and zlib's braided
/// tables) prescribe:
///
/// ```text
/// c = tables[0][c & 0xff] ^ (c >> 8)
/// ```
///
/// Because both `build.rs` and the consuming `src/checksum/crc32.rs` use this
/// same construction/consumption pair, the final CRC-32 values are identical to
/// canonical zlib regardless of which acceleration width is used internally
/// (the method is mathematically equivalent to the byte-at-a-time fallback).
fn make_slice_by8_tables(basic: &[u32; 256]) -> [[u32; 256]; 8] {
    let mut tables = [[0u32; 256]; 8];
    tables[0] = *basic;
    for n in 0..256 {
        let mut c = basic[n];
        // Fill rows 1..8 of column `n`; each row folds in one more byte-wise
        // reduction step. `c` carries the running value across the rows.
        for row in tables.iter_mut().skip(1) {
            c = basic[(c & 0xff) as usize] ^ (c >> 8);
            row[n] = c;
        }
    }
    tables
}

/// Return `a(x) * b(x) mod p(x)`, with all polynomials in reflected form — the
/// exact port of `multmodp()` from `crc32.c`. Used only to seed [`X2N_TABLE`],
/// the table of `x^(2^n) mod p(x)` powers that `crc32_combine()` relies on.
fn multmodp(a: u32, mut b: u32) -> u32 {
    let mut m: u32 = 1 << 31;
    let mut p: u32 = 0;
    loop {
        if a & m != 0 {
            p ^= b;
            if a & (m - 1) == 0 {
                break;
            }
        }
        m >>= 1;
        b = if b & 1 != 0 { (b >> 1) ^ POLY } else { b >> 1 };
    }
    p
}

/// Build the 32-entry table of `x^(2^n) mod p(x)` powers, the faithful port of
/// the `x2n_table` loop in `make_crc_table()`. Entry 0 is `x^1` (`0x40000000`);
/// each subsequent entry squares the previous one modulo the polynomial. These
/// values back the `crc32_combine*` family in `src/checksum/crc32.rs` and match
/// upstream `crc32.h`'s `x2n_table[]` exactly.
fn make_x2n_table() -> [u32; 32] {
    let mut x2n = [0u32; 32];
    let mut p: u32 = 1 << 30; // x^1 in reflected form == 0x40000000
    x2n[0] = p;
    for slot in x2n.iter_mut().skip(1) {
        p = multmodp(p, p);
        *slot = p;
    }
    x2n
}

/// Compute a one-shot CRC-32 of `data` using the basic table, used purely as a
/// build-time self-check. Mirrors the standard table-driven inner loop:
/// pre/post-condition with `0xFFFF_FFFF`, fold one byte at a time.
fn crc32_oneshot(table: &[u32; 256], data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFF_FFFF;
    for &byte in data {
        crc = table[((crc ^ u32::from(byte)) & 0xff) as usize] ^ (crc >> 8);
    }
    !crc
}

/// Append `values` to `out` as comma-separated lowercase hex literals, five per
/// line, each line prefixed with `indent`. A trailing newline is always added.
fn push_u32_values(out: &mut String, values: &[u32], indent: &str) {
    for (i, &v) in values.iter().enumerate() {
        if i % 5 == 0 {
            out.push_str(indent);
        }
        // Writing to a `String` is infallible.
        write!(out, "0x{v:08x}").unwrap();
        if i + 1 != values.len() {
            out.push(',');
            if (i + 1) % 5 == 0 {
                out.push('\n');
            } else {
                out.push(' ');
            }
        }
    }
    out.push('\n');
}

/// Render a flat `[u32; 256]` table as a `pub(crate) static` definition.
fn render_flat_table(out: &mut String, name: &str, table: &[u32; 256]) {
    out.push_str("#[allow(dead_code)]\n");
    writeln!(out, "pub(crate) static {name}: [u32; 256] = [").unwrap();
    push_u32_values(out, table, "    ");
    out.push_str("];\n\n");
}

/// Render a two-dimensional `[[u32; 256]; 8]` table as a `pub(crate) static`.
fn render_2d_table(out: &mut String, name: &str, tables: &[[u32; 256]; 8]) {
    out.push_str("#[allow(dead_code)]\n");
    writeln!(out, "pub(crate) static {name}: [[u32; 256]; 8] = [").unwrap();
    for (k, sub) in tables.iter().enumerate() {
        out.push_str("    [\n");
        push_u32_values(out, sub, "        ");
        out.push_str("    ]");
        if k + 1 != tables.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}

/// Render the 32-entry `x2n` power table as a `pub(crate) static`.
fn render_x2n_table(out: &mut String, name: &str, table: &[u32; 32]) {
    out.push_str("#[allow(dead_code)]\n");
    writeln!(out, "pub(crate) static {name}: [u32; 32] = [").unwrap();
    push_u32_values(out, table, "    ");
    out.push_str("];\n");
}

/// Generate every CRC-32 table, validate it against known-good zlib values, and
/// write the result to `${OUT_DIR}/crc32_table.rs`.
///
/// The emitted file defines three `pub(crate)` statics, all annotated
/// `#[allow(dead_code)]` so the consuming module may use any subset without
/// tripping the `dead_code` lint:
///
/// * `CRC_TABLE_0: [u32; 256]` — the canonical byte-wise table.
/// * `CRC_TABLE:   [[u32; 256]; 8]` — the slice-by-8 acceleration tables
///   (`CRC_TABLE[0]` equals `CRC_TABLE_0`).
/// * `X2N_TABLE:   [u32; 32]` — `x^(2^n) mod p(x)` powers for `crc32_combine`.
///
/// The self-checks use `assert!`/`assert_eq!` (always on, in debug *and*
/// release): because these tables drive a wire-format checksum, a wrong table
/// must fail the build loudly rather than silently ship a corrupt artifact.
fn write_crc_tables(out_dir: &Path) {
    let basic = make_basic_table();
    let slice_by8 = make_slice_by8_tables(&basic);
    let x2n = make_x2n_table();

    // --- Build-time correctness gate (must match canonical zlib exactly) ---
    assert_eq!(basic[0], 0x0000_0000, "CRC basic table[0] mismatch");
    assert_eq!(basic[1], 0x7707_3096, "CRC basic table[1] mismatch");
    assert_eq!(basic[2], 0xEE0E_612C, "CRC basic table[2] mismatch");
    assert_eq!(basic[3], 0x9909_51BA, "CRC basic table[3] mismatch");
    assert_eq!(basic[4], 0x076D_C419, "CRC basic table[4] mismatch");
    // `CRC_TABLE[0]` must equal the flat basic table.
    assert!(
        slice_by8[0] == basic,
        "slice-by-8 table[0] must equal basic table"
    );
    // The x2n power table must match upstream `crc32.h` at both ends.
    assert_eq!(x2n[0], 0x4000_0000, "x2n_table[0] mismatch");
    assert_eq!(x2n[5], 0xEDB8_8320, "x2n_table[5] mismatch");
    assert_eq!(x2n[31], 0xC4E2_2C3C, "x2n_table[31] mismatch");
    // The canonical CRC-32 of the ASCII string "123456789" is 0xCBF43926.
    assert_eq!(
        crc32_oneshot(&basic, b"123456789"),
        0xCBF4_3926,
        "CRC-32 of \"123456789\" must be 0xCBF43926"
    );

    // --- Render the generated module ---------------------------------------
    let mut out = String::with_capacity(96 * 1024);
    out.push_str(
        "// @generated by build.rs — DO NOT EDIT.\n\
         //\n\
         // IEEE reflected CRC-32 lookup tables (polynomial 0xEDB88320),\n\
         // re-derived at build time to be bit-identical to upstream zlib\n\
         // `crc32.h`. Included by `src/checksum/crc32.rs` via\n\
         // `include!(concat!(env!(\"OUT_DIR\"), \"/crc32_table.rs\"));`.\n\n",
    );
    render_flat_table(&mut out, "CRC_TABLE_0", &basic);
    render_2d_table(&mut out, "CRC_TABLE", &slice_by8);
    render_x2n_table(&mut out, "X2N_TABLE", &x2n);

    let dest = out_dir.join("crc32_table.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}

// ===========================================================================
// Phase B / C — cbindgen C-header emission (best-effort, opt-in)
// ===========================================================================

/// Decide whether the C header should be (re)generated on this build.
///
/// Header generation is **opt-in**, because the default `cargo build` /
/// `cargo test` flow does not need the header and `cargo test` even prefers it
/// absent (the dev-only `flate2` oracle links canonical C zlib, whose symbols
/// could clash with the crate's own `#[no_mangle]` exports at test-link time).
/// It is enabled by either:
///
/// * setting the `ZLIB_RS_GENERATE_HEADER` environment variable (any value), or
/// * enabling a `capi` / `ffi` Cargo feature, should one ever be added to gate
///   the FFI surface — Cargo exposes those as `CARGO_FEATURE_CAPI` /
///   `CARGO_FEATURE_FFI` to the build script.
///
/// When neither is present the function returns `false` and Phase B is skipped
/// silently (this is the normal, expected path).
fn header_generation_requested() -> bool {
    env::var_os("ZLIB_RS_GENERATE_HEADER").is_some()
        || env::var_os("CARGO_FEATURE_CAPI").is_some()
        || env::var_os("CARGO_FEATURE_FFI").is_some()
}

/// Invoke cbindgen to produce the C header from `src/ffi.rs`.
///
/// This routine is intentionally **infallible from the build's perspective**:
/// every failure mode (missing `src/ffi.rs`, unreadable `cbindgen.toml`, a
/// cbindgen parse/generate error, or an I/O error while writing) is reported
/// through `cargo:warning=` and then swallowed, so a header problem can never
/// break the core library build. The header is written to the stable path
/// `${CARGO_MANIFEST_DIR}/include/zlib-rs.h` and additionally mirrored into
/// `${OUT_DIR}` for tooling that prefers the build-output tree.
fn generate_c_header(manifest_dir: &Path, out_dir: &Path) {
    // `src/ffi.rs` may not exist yet during an early/partial build. If it is
    // absent there is nothing to bind, so warn and bail out gracefully.
    let ffi_src = manifest_dir.join("src").join("ffi.rs");
    if !ffi_src.exists() {
        println!(
            "cargo:warning=zlib-rs: C header generation requested but {} is absent; skipping cbindgen.",
            ffi_src.display()
        );
        return;
    }

    // Load `cbindgen.toml` from the crate root; fall back to cbindgen's own
    // defaults (still keyed to the crate root) if it cannot be read.
    let config_path = manifest_dir.join("cbindgen.toml");
    let config = match cbindgen::Config::from_file(&config_path) {
        Ok(cfg) => cfg,
        Err(e) => {
            println!(
                "cargo:warning=zlib-rs: could not read {}: {e}; using cbindgen defaults.",
                config_path.display()
            );
            cbindgen::Config::from_root_or_default(manifest_dir)
        }
    };

    match cbindgen::Builder::new()
        .with_crate(manifest_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            // Render the generated header into an in-memory buffer ONCE, then
            // write it out with explicit, fallible `fs::write` calls.
            //
            // We deliberately avoid `Bindings::write_to_file`: in cbindgen
            // 0.28.0 that helper performs its directory creation and file write
            // with internal `unwrap()`s, so any I/O failure (a read-only source
            // tree, a permissions problem, a full disk) would PANIC and hard-
            // fail the entire crate build. Header emission is required to
            // degrade gracefully (AAP §0.3.1 robustness; the header must never
            // be able to break the core library build), so instead we use the
            // fallible `Bindings::write` to a `Vec<u8>` and surface every write
            // failure through `cargo:warning=` without ever panicking.
            let mut rendered: Vec<u8> = Vec::new();
            bindings.write(&mut rendered);

            // Stable, source-tree location for downstream C consumers.
            let include_dir = manifest_dir.join("include");
            match fs::create_dir_all(&include_dir) {
                Ok(()) => {
                    let header_path = include_dir.join("zlib-rs.h");
                    if let Err(e) = fs::write(&header_path, &rendered) {
                        println!(
                            "cargo:warning=zlib-rs: could not write {}: {e}.",
                            header_path.display()
                        );
                    }
                }
                Err(e) => {
                    println!(
                        "cargo:warning=zlib-rs: could not create {}: {e}.",
                        include_dir.display()
                    );
                }
            }

            // Mirror into OUT_DIR as well (always writable, under `target/`).
            let out_header = out_dir.join("zlib_rs.h");
            if let Err(e) = fs::write(&out_header, &rendered) {
                println!(
                    "cargo:warning=zlib-rs: could not write {}: {e}.",
                    out_header.display()
                );
            }
        }
        Err(e) => {
            // The most common benign cause is `src/ffi.rs` not yet existing or
            // the FFI surface being feature-gated off. Never hard-fail here.
            println!("cargo:warning=zlib-rs: cbindgen header generation skipped: {e}");
        }
    }
}

// ===========================================================================
// Phase D — variadic `gzprintf`/`gzvprintf` C shim (opt-in, capi + gz-io only)
// ===========================================================================

/// Decide whether the variadic `gzprintf`/`gzvprintf` C shim should be compiled
/// and linked on this build.
///
/// The shim (`csrc/gzprintf.c`) supplies the two canonical *variadic* zlib
/// symbols that stable Rust cannot express (`c_variadic` is unstable). It is
/// only meaningful when BOTH:
///
/// * the `capi` feature is on — the `#[no_mangle] extern "C"` drop-in surface
///   in `src/ffi.rs` (including the `zlibrs_gzprintf_write` callback the shim
///   calls back into) is compiled and exported; and
/// * the `gz-io` feature is on — the gzip FILE-I/O engine the callback drives
///   (and hence the `zlibrs_gzprintf_write` symbol itself, which is
///   `#[cfg(feature = "gz-io")]`) actually exists.
///
/// Cargo surfaces enabled features to the build script as `CARGO_FEATURE_<NAME>`
/// environment variables (with `-` mapped to `_`). When either feature is
/// absent the shim is skipped entirely, so the default pure-Rust build compiles
/// and links NO C and the shipped crate keeps its zero-C-dependency guarantee
/// (AAP §0.7.2).
fn gzprintf_shim_requested() -> bool {
    env::var_os("CARGO_FEATURE_CAPI").is_some() && env::var_os("CARGO_FEATURE_GZ_IO").is_some()
}

/// Compile `csrc/gzprintf.c` into a small static archive and link it into the
/// crate.
///
/// The shim performs C variadic formatting (`vsnprintf` into a bounded buffer)
/// under the internal symbols `zlibrs_gzprintf_impl` / `zlibrs_gzvprintf_impl`,
/// and then calls the safe-Rust `zlibrs_gzprintf_write` callback exported by
/// `src/ffi.rs` to perform the actual compressed write. The *public* `gzprintf`
/// / `gzvprintf` symbols are the `#[unsafe(naked)]` Rust trampolines in
/// `src/ffi.rs` that tail-`jmp` to these C implementations. `cc` drives the
/// system C compiler (gcc/clang); it is a build-time tool only and is never
/// linked into the library — only the resulting object code is.
///
/// A plain `cargo:rustc-link-lib=static=…` (emitted by `cc::Build::compile`) is
/// sufficient: the Rust naked trampolines reference the C implementations via
/// the assembler `sym` operand, so the linker pulls the shim object in to
/// resolve those references, and `--gc-sections` keeps the implementations
/// because they are reachable from the exported `gzprintf`/`gzvprintf` symbols.
/// No `+whole-archive` or `--undefined` coaxing is required.
fn compile_gzprintf_shim(manifest_dir: &Path) {
    let shim = manifest_dir.join("csrc").join("gzprintf.c");
    if !shim.exists() {
        // Should never happen in a well-formed tree, but degrade loudly rather
        // than emit a confusing linker error if the source is missing.
        println!(
            "cargo:warning=zlib-rs: gzprintf C shim requested but {} is absent; \
             the variadic gzprintf/gzvprintf symbols will be unavailable.",
            shim.display()
        );
        return;
    }

    cc::Build::new()
        .file(&shim)
        // Surface compiler diagnostics but do not fail the build on benign
        // platform warnings; the shim itself is warning-clean under -Wall.
        .warnings(true)
        .compile("zlibrs_gzprintf_shim");
}

// ===========================================================================
// Entry point
// ===========================================================================

fn main() {
    // Re-run triggers. Single-colon `cargo:` directives are the maximally
    // portable form and are emitted unconditionally so cargo's change tracking
    // stays correct whether or not the header is generated this run.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/ffi.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-changed=csrc/gzprintf.c");
    println!("cargo:rerun-if-env-changed=ZLIB_RS_GENERATE_HEADER");

    // Phase A is mandatory: the crate cannot compute correct checksums without
    // these tables, so any failure here legitimately aborts the build.
    let out_dir = PathBuf::from(
        env::var_os("OUT_DIR").expect("OUT_DIR is always set by cargo for build scripts"),
    );
    write_crc_tables(&out_dir);

    // `CARGO_MANIFEST_DIR` is the crate root; both the (opt-in) header emission
    // and the (opt-in) C-shim compilation are anchored to it.
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .expect("CARGO_MANIFEST_DIR is always set by cargo for build scripts"),
    );

    // Phase B/C is best-effort and opt-in.
    if header_generation_requested() {
        generate_c_header(&manifest_dir, &out_dir);
    }

    // Phase D is opt-in: only when the C-ABI drop-in (`capi`) AND the gzip
    // FILE-I/O engine (`gz-io`) are both enabled does the variadic
    // gzprintf/gzvprintf shim have both a reason to exist and a callback symbol
    // to link against. The default pure-Rust build skips it entirely.
    if gzprintf_shim_requested() {
        compile_gzprintf_shim(&manifest_dir);
    }
}
