all:
	-@echo "Please use ./configure first.  Thank you."

distclean:
	make -f Makefile.in distclean

# The Rust targets work before ./configure has run, so they are forwarded
# rather than refused.  They stage a library named from the ZLIB_VERSION in
# zlib.h, not from Makefile.in's unconfigured SHAREDLIBV default, so the name
# is right on this path too.  This file is regenerated by `distclean'; keep it
# and that recipe in step.
rust:
	$(MAKE) -f Makefile.in rust

rust-test:
	$(MAKE) -f Makefile.in rust-test

rust-symbols:
	$(MAKE) -f Makefile.in rust-symbols

rust-clean:
	$(MAKE) -f Makefile.in rust-clean
