all:
	-@echo "Please use ./configure first.  Thank you."

distclean:
	make -f Makefile.in distclean

# The Rust targets work before ./configure has run, so they are forwarded
# rather than refused.  They stage a library named from the ZLIB_VERSION in
# zlib.h, not from Makefile.in's unconfigured SHAREDLIBV default, and they
# relink it through zlib.map with flags Makefile.in supplies itself, so the
# name, the SONAME and the 16 symbol version nodes are all right on this path
# too -- verified here: 111 dynamic globals, identical to the C library's.
# This file is regenerated by `distclean'; keep it and that recipe in step.
#
# .PHONY is REQUIRED, not tidiness.  `rust' is also the name of a directory in
# this tree -- rust/README.md, the developer guide -- and a target whose name
# matches an existing file or directory with no prerequisites is considered up
# to date, so without this line `make rust' prints "'rust' is up to date" and
# runs nothing while still exiting 0.  That is a silent no-op, which is worse
# than an error.  The whole family is declared rather than just `rust', so a
# later addition under any of these names cannot reintroduce the same trap.
.PHONY: all distclean rust rust-test rust-symbols rust-header rust-msrv rust-clean

rust:
	$(MAKE) -f Makefile.in rust

rust-pc:
	$(MAKE) -f Makefile.in rust-pc

rust-test:
	$(MAKE) -f Makefile.in rust-test

rust-symbols:
	$(MAKE) -f Makefile.in rust-symbols

rust-header:
	$(MAKE) -f Makefile.in rust-header

rust-msrv:
	$(MAKE) -f Makefile.in rust-msrv

rust-clean:
	$(MAKE) -f Makefile.in rust-clean
