//! CRC-32 (IEEE 802.3) checksum — a safe, pure-Rust, bit-identical port of the
//! upstream C `crc32.c` / `crc32.h`.
//!
//! This module computes the reflected CRC-32 used by the zlib and gzip wire
//! formats (gzip per RFC 1952). The polynomial is the reflected IEEE 802.3
//! generator [`POLY`] (`0xedb88320`, i.e. `x^32 + x^26 + x^23 + x^22 + x^16 +
//! x^12 + x^11 + x^10 + x^8 + x^7 + x^5 + x^4 + x^2 + x + 1`, with the `x^32`
//! term implied).
//!
//! # Bit-exactness
//!
//! Producing **byte-identical** output to C zlib is a hard requirement, so this
//! module is validated against the canonical CRC-32/ISO-HDLC check value
//! (`crc32(0, b"123456789") == 0xcbf4_3926`) and against streaming/associativity
//! invariants. Two interchangeable back ends are provided, and both yield the
//! exact same IEEE CRC-32 values:
//!
//! * **SIMD path** (`feature = "simd"`, the crate default): delegates to the
//!   hardware-accelerated [`crc32fast`] crate, mirroring the optimized braided /
//!   instruction-based paths in the C source.
//! * **Scalar path** (`--no-default-features`, `no_std` / `Z_SOLO`-style builds):
//!   the classic byte-wise table algorithm driven by the build-time generated
//!   lookup table. This is the correctness-guaranteeing fallback.
//!
//! # Returned value
//!
//! Every function here returns the **raw `u32`** CRC. Serializing the value into
//! a little-endian gzip trailer (or any other on-the-wire form) is the caller's
//! responsibility; this module is deliberately format-agnostic and depends on no
//! other module in the crate.
//!
//! # Safety
//!
//! The whole crate is `#![forbid(unsafe_code)]`. This module contains **zero**
//! `unsafe` — even the scalar table loop uses checked slice indexing — and is
//! fully `no_std`-compatible (it touches only `core`).

/// The reflected IEEE 802.3 CRC-32 polynomial, `p(x)` with the `x^32` term
/// implied. Identical to the C `#define POLY 0xedb88320` in `crc32.c`.
const POLY: u32 = 0xedb8_8320;

// ---------------------------------------------------------------------------
// Phase A — byte-wise lookup table (build-script generated) + name alias
// ---------------------------------------------------------------------------

// Pull in the 256-entry byte-wise CRC-32 table generated by the sibling
// `zlib-rs/build.rs` into `${OUT_DIR}/crc32_table.rs`. The generated file
// defines exactly:
//
//     pub static CRC32_TABLE: [u32; 256] = [ 0x00000000, 0x77073096, ... ];
//
// The table is mathematically fixed by `POLY`, reproducing the `crc_table[]` of
// the upstream (generated) `crc32.h` without vendoring its ~591 KB. It is
// included unconditionally — regardless of the `simd` feature — because
// `get_crc_table()` and the `CRC_TABLE` import contract must always resolve.
//
// `env!`, `concat!`, and `include!` are `core` macros and are both `no_std`- and
// `forbid(unsafe_code)`-clean.
include!(concat!(env!("OUT_DIR"), "/crc32_table.rs"));

/// Alias re-export satisfying the AAP §0.4.2 cross-module import contract, under
/// which dependents reference the table as `crate::checksum::crc32::CRC_TABLE`.
///
/// The build script emits the table as `CRC32_TABLE`; both
/// `crate::checksum::crc32::CRC32_TABLE` and `crate::checksum::crc32::CRC_TABLE`
/// now resolve to the very same `static`.
pub use self::CRC32_TABLE as CRC_TABLE;

// ---------------------------------------------------------------------------
// Phase B — get_crc_table() (public C-API parity)
// ---------------------------------------------------------------------------

/// Return a reference to the 256-entry byte-wise CRC-32 lookup table.
///
/// Mirrors the C `get_crc_table()`, which hands back the byte-wise `crc_table`.
/// Available on both feature paths. Unlike the C version there is no run-time
/// table initialization or `once` guard: the table is a compile-time `static`.
pub fn get_crc_table() -> &'static [u32; 256] {
    &CRC32_TABLE
}

// ---------------------------------------------------------------------------
// Phase C — core CRC computation (dual path) + thin `crc32` wrapper
// ---------------------------------------------------------------------------

/// Update a running CRC-32 with `buf` and return the new value (SIMD path).
///
/// Faithful to C `crc32_z(crc, buf, len)`: `crc` is a *continuing* CRC (use `0`
/// to start a fresh computation), and the returned value is the post-conditioned
/// IEEE CRC-32 over the concatenation of all bytes seen so far.
///
/// This default path defers to [`crc32fast`], which selects a hardware
/// accelerated implementation at run time and applies the standard pre/post
/// conditioning internally.
#[cfg(feature = "simd")]
pub fn crc32_z(crc: u32, buf: &[u8]) -> u32 {
    // A zero-length update leaves a continuing CRC unchanged, matching the C
    // behavior of returning `crc` when there is nothing to process. Returning
    // early also avoids constructing a hasher for the common empty case.
    if buf.is_empty() {
        return crc;
    }

    // `new_with_initial` (not `new`) is the correct *continuation* constructor:
    // it seeds the hasher with the externally visible CRC value so that
    // `crc32_z(crc32_z(0, a), b) == crc32_z(0, a ++ b)`.
    let mut hasher = crc32fast::Hasher::new_with_initial(crc);
    hasher.update(buf);
    hasher.finalize()
}

/// Update a running CRC-32 with `buf` and return the new value (scalar path).
///
/// This is the `no_std` / `--no-default-features` fallback. It is the classic
/// byte-wise table algorithm: one's-complement pre-conditioning, the per-byte
/// reduction `crc = (crc >> 8) ^ table[(crc ^ byte) & 0xff]`, then
/// one's-complement post-conditioning — exactly the C inner step. Bytes are
/// processed eight at a time (mirroring the C 8-way unrolled loop) with a
/// trailing remainder; the result is provably identical to a one-byte-at-a-time
/// loop and to the SIMD path.
#[cfg(not(feature = "simd"))]
pub fn crc32_z(crc: u32, buf: &[u8]) -> u32 {
    // Pre-condition (C: `crc = (~crc) & 0xffffffff`). On `u32`, `!crc` already
    // masks to 32 bits, so the explicit `& 0xffffffff` is a no-op and is omitted.
    let mut crc = !crc;

    // Eight bytes per iteration. `chunks_exact` guarantees every index below is
    // in-bounds, so the indexing needs no `unsafe`.
    let mut chunks = buf.chunks_exact(8);
    for chunk in &mut chunks {
        crc = crc32_step(crc, chunk[0]);
        crc = crc32_step(crc, chunk[1]);
        crc = crc32_step(crc, chunk[2]);
        crc = crc32_step(crc, chunk[3]);
        crc = crc32_step(crc, chunk[4]);
        crc = crc32_step(crc, chunk[5]);
        crc = crc32_step(crc, chunk[6]);
        crc = crc32_step(crc, chunk[7]);
    }

    // Trailing 0..=7 bytes.
    for &byte in chunks.remainder() {
        crc = crc32_step(crc, byte);
    }

    // Post-condition (C: `crc ^ 0xffffffff`).
    !crc
}

/// Advance the (already pre-conditioned) CRC register by a single byte using the
/// byte-wise table. Used only by the scalar [`crc32_z`].
#[cfg(not(feature = "simd"))]
#[inline]
fn crc32_step(crc: u32, byte: u8) -> u32 {
    let index = ((crc ^ (byte as u32)) & 0xff) as usize;
    (crc >> 8) ^ CRC32_TABLE[index]
}

/// Update a running CRC-32 with `buf` and return the new value.
///
/// Thin wrapper over [`crc32_z`], mirroring the C `crc32` → `crc32_z`
/// delegation. Pass `crc == 0` to begin a fresh CRC.
pub fn crc32(crc: u32, buf: &[u8]) -> u32 {
    crc32_z(crc, buf)
}

// ---------------------------------------------------------------------------
// Phase D — GF(2) polynomial arithmetic for CRC combination
//
// These helpers are pure arithmetic over GF(2) and are *feature-independent*:
// CRC combination never uses `crc32fast`. `multmodp` is a `const fn` so the
// powers-of-x table can be a compile-time `const`, eliminating the C
// `make_crc_table()` run-time initialization (and any `once`/locking) entirely.
// ---------------------------------------------------------------------------

/// Return `a(x) * b(x) mod p(x)`, where `p(x)` is the reflected CRC polynomial
/// [`POLY`]. Faithful port of C `multmodp`.
///
/// For speed (and to guarantee termination) the C contract requires `a != 0`:
/// the loop exits when `m` reaches the lowest set bit of `a`. Every caller in
/// this module upholds that invariant (`X2N_TABLE` squares non-zero values,
/// `x2nmodp` indexes the all-non-zero `X2N_TABLE`, and `crc32_combine_op`
/// short-circuits `op == 0` before calling).
const fn multmodp(a: u32, b: u32) -> u32 {
    // `m` walks from the most-significant bit downward, selecting one bit of `a`
    // per iteration; `p` accumulates the product; `b` is repeatedly multiplied
    // by `x` (a reflected right-shift, folding in `POLY` on carry-out).
    let mut m: u32 = 1 << 31;
    let mut p: u32 = 0;
    let mut b = b;
    loop {
        if a & m != 0 {
            p ^= b;
            // No lower bits of `a` remain set: the product is complete.
            if a & (m - 1) == 0 {
                break;
            }
        }
        m >>= 1;
        b = if b & 1 != 0 { (b >> 1) ^ POLY } else { b >> 1 };
    }
    p
}

/// Compile-time table of `x^(2^n) mod p(x)` for `n` in `0..32`, faithfully
/// reproducing the `x2n_table[32]` built by the C `make_crc_table()`.
///
/// `X2N_TABLE[0]` is `x^1` and each subsequent entry squares the previous one
/// (`x^(2^n) = (x^(2^(n-1)))^2`). Because every entry is non-zero, it is always a
/// valid first argument to [`multmodp`].
const X2N_TABLE: [u32; 32] = {
    let mut table = [0u32; 32];
    let mut p: u32 = 1 << 30; // x^1
    table[0] = p;
    let mut n = 1usize;
    while n < 32 {
        p = multmodp(p, p); // square: x^(2^n) = (x^(2^(n-1)))^2
        table[n] = p;
        n += 1;
    }
    table
};

/// Return `x^(n * 2^k) mod p(x)`. Faithful port of C `x2nmodp(n, k)`.
///
/// `n` is treated as non-negative (the C source uses a signed `z_off64_t`; the
/// `len2 < 0 → 0` sentinel is handled by [`crc32_combine_gen`]'s callers / the
/// FFI shim, never here). `k` indexes [`X2N_TABLE`] modulo 32.
const fn x2nmodp(mut n: u64, mut k: u32) -> u32 {
    let mut p: u32 = 1 << 31; // x^0 == 1
    while n != 0 {
        if n & 1 != 0 {
            p = multmodp(X2N_TABLE[(k & 31) as usize], p);
        }
        n >>= 1;
        k = k.wrapping_add(1);
    }
    p
}

// ---------------------------------------------------------------------------
// Phase E — CRC combination public API
// ---------------------------------------------------------------------------

/// Generate the combination operator for appending a second message of length
/// `len2` bytes. Faithful port of C `crc32_combine_gen64`.
///
/// The result is `x^(len2 * 8) mod p(x)`, suitable for passing to
/// [`crc32_combine_op`]. The C `len2 < 0 → return 0` guard applies to the signed
/// `z_off_t`/`z_off64_t` C entry points and is enforced at the FFI boundary;
/// this safe-Rust API takes an unsigned `u64`.
pub const fn crc32_combine_gen(len2: u64) -> u32 {
    x2nmodp(len2, 3)
}

/// Combine two CRCs given a precomputed operator `op` (from
/// [`crc32_combine_gen`]). Faithful port of C `crc32_combine_op`.
///
/// Returns `0` when `op == 0` (matching C, and also keeping the [`multmodp`]
/// `a != 0` precondition intact). Otherwise returns
/// `multmodp(op, crc1) ^ crc2`. The C `& 0xffffffff` masks are no-ops on `u32`
/// and are omitted.
pub const fn crc32_combine_op(crc1: u32, crc2: u32, op: u32) -> u32 {
    if op == 0 {
        return 0;
    }
    multmodp(op, crc1) ^ crc2
}

/// Combine the CRC-32 of two messages into the CRC-32 of their concatenation.
///
/// Given `crc1 = crc32(0, A)`, `crc2 = crc32(0, B)`, and `len2 = B.len()`,
/// returns `crc32(0, A ++ B)` without re-scanning the data. Faithful port of C
/// `crc32_combine64` (and, for in-range lengths, `crc32_combine`); `len2: u64`
/// serves both the 32- and 64-bit C symbols.
pub const fn crc32_combine(crc1: u32, crc2: u32, len2: u64) -> u32 {
    crc32_combine_op(crc1, crc2, crc32_combine_gen(len2))
}

// Compile-time proof that the CRC-combination helpers are usable in `const`
// context, as the CP1 performance contract requires. If any of `x2nmodp`,
// `crc32_combine_gen`, `crc32_combine_op`, or `crc32_combine` were downgraded
// from `const fn`, this block would fail to compile.
const _: () = {
    // `crc32_combine_gen(0)` is the reflected identity polynomial `x^0 = 1`.
    assert!(crc32_combine_gen(0) == 1u32 << 31);
    // `op == 0` short-circuits to 0 (and upholds `multmodp`'s `a != 0` precond).
    assert!(crc32_combine_op(1, 2, 0) == 0);
    // The full combine of two empty CRCs is 0.
    assert!(crc32_combine(0, 0, 0) == 0);
};

// ---------------------------------------------------------------------------
// Phase F — unit tests (known-answer + invariants)
//
// The functions under test are `no_std`-clean; only tests that need heap
// allocation (`Vec` / `[..].concat()`) are gated behind `feature = "std"` so
// that `cargo test --no-default-features` (the scalar path) still builds. The
// same known-answer assertions run on BOTH feature paths, proving the SIMD and
// scalar implementations are bit-identical to C zlib.
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_input_returns_initial_crc() {
        // The initial CRC value is 0, and an empty update returns it unchanged.
        assert_eq!(crc32(0, b""), 0);
        // A non-zero continuing CRC is likewise unchanged by an empty update.
        assert_eq!(crc32(0x1234_5678, b""), 0x1234_5678);
        assert_eq!(crc32_z(0xffff_ffff, b""), 0xffff_ffff);
    }

    #[test]
    fn canonical_check_value() {
        // CRC-32/ISO-HDLC check value over the ASCII string "123456789".
        assert_eq!(crc32(0, b"123456789"), 0xcbf4_3926);
        // `crc32` and `crc32_z` are the same computation.
        assert_eq!(crc32_z(0, b"123456789"), 0xcbf4_3926);
    }

    #[test]
    fn table_known_values() {
        // Canonical first entries of the reflected-`0xedb88320` byte-wise table.
        assert_eq!(get_crc_table()[0], 0x0000_0000);
        assert_eq!(get_crc_table()[1], 0x7707_3096);
        assert_eq!(get_crc_table()[2], 0xee0e_612c);
        assert_eq!(get_crc_table()[3], 0x9909_51ba);
        assert_eq!(get_crc_table()[4], 0x076d_c419);
    }

    #[test]
    fn crc_table_alias_resolves() {
        // Proves the AAP §0.4.2 `CRC_TABLE` alias resolves to the same table.
        assert_eq!(CRC_TABLE[3], 0x9909_51ba);
        assert_eq!(CRC_TABLE[1], get_crc_table()[1]);
        assert_eq!(CRC_TABLE.len(), 256);
    }

    #[test]
    fn streaming_associativity() {
        // Splitting the input at any point and chaining the CRC must reproduce
        // the whole-buffer CRC. This exercises the running-CRC continuation on
        // whichever path is compiled.
        let data: &[u8] = b"The quick brown fox jumps over the lazy dog.";
        let whole = crc32(0, data);
        for k in 0..=data.len() {
            let part1 = crc32(0, &data[..k]);
            let part2 = crc32(part1, &data[k..]);
            assert_eq!(part2, whole, "split at {k}");
        }
    }

    #[test]
    fn nonzero_initial_continuation() {
        // crc32(crc32(0, A), B) == crc32(0, A ++ B); verifies that a non-zero
        // seed continues the computation (critical for the SIMD path's
        // `new_with_initial`). Uses a fixed stack buffer to stay `no_std`-clean.
        let a: &[u8] = b"abcdefgh";
        let b: &[u8] = b"ijklmnopqrstuv";
        let mut both = [0u8; 22];
        both[..a.len()].copy_from_slice(a);
        both[a.len()..].copy_from_slice(b);
        assert_eq!(crc32(crc32(0, a), b), crc32(0, &both));
    }

    #[test]
    fn combine_identity_fixed() {
        // crc32_combine(crc(A), crc(B), len(B)) == crc(A ++ B), using a fixed
        // stack buffer so the test runs on the `no_std` scalar path too.
        let a: &[u8] = b"hello, ";
        let b: &[u8] = b"world!";
        let mut both = [0u8; 13];
        both[..a.len()].copy_from_slice(a);
        both[a.len()..].copy_from_slice(b);

        let crc_a = crc32(0, a);
        let crc_b = crc32(0, b);
        let combined = crc32_combine(crc_a, crc_b, b.len() as u64);
        assert_eq!(combined, crc32(0, &both));
    }

    #[test]
    fn combine_with_empty_second_part() {
        // Combining with an empty B (len2 == 0) must leave crc(A) unchanged.
        let a: &[u8] = b"some data to checksum";
        let crc_a = crc32(0, a);
        assert_eq!(crc32_combine(crc_a, crc32(0, b""), 0), crc_a);
    }

    #[test]
    fn combine_op_zero_short_circuits() {
        // op == 0 short-circuits to 0 (matching C and preserving the
        // `multmodp` `a != 0` precondition).
        assert_eq!(crc32_combine_op(0x1234_5678, 0xdead_beef, 0), 0);
    }

    #[test]
    fn combine_gen_zero_is_multiplicative_identity() {
        // crc32_combine_gen(0) yields x^0 == 1 (represented as 0x8000_0000),
        // the multiplicative identity: combining through it returns crc1.
        let op = crc32_combine_gen(0);
        assert_eq!(op, 0x8000_0000);
        assert_eq!(crc32_combine_op(0x0bad_f00d, 0, op), 0x0bad_f00d);
    }

    // Heap-allocating cases are gated so `--no-default-features` test builds
    // (which exercise the `no_std` scalar path) still compile.
    #[cfg(feature = "std")]
    #[test]
    fn combine_identity_dynamic() {
        fn check(a: &[u8], b: &[u8]) {
            let combined = crc32_combine(crc32(0, a), crc32(0, b), b.len() as u64);
            let whole = crc32(0, &[a, b].concat());
            assert_eq!(combined, whole, "combine {a:?} || {b:?}");
        }

        check(b"", b"");
        check(b"a", b"");
        check(b"", b"b");
        check(b"foo", b"bar");
        check(b"The quick brown ", b"fox jumps over the lazy dog");
        check(&[0u8; 257], &[0xffu8; 131]);
    }

    // A larger pseudo-random round-trip that also crosses the scalar path's
    // 8-byte unroll boundary many times. Gated only because it allocates.
    #[cfg(feature = "std")]
    #[test]
    fn long_buffer_split_consistency() {
        let mut data = Vec::with_capacity(1000);
        let mut state: u32 = 0x1234_5678;
        for _ in 0..1000 {
            // Simple xorshift to fill with non-trivial bytes (test-only).
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;
            data.push((state & 0xff) as u8);
        }
        let whole = crc32(0, &data);
        for &k in &[0usize, 1, 7, 8, 9, 64, 255, 256, 511, 999, 1000] {
            let combined = crc32_combine(
                crc32(0, &data[..k]),
                crc32(0, &data[k..]),
                (data.len() - k) as u64,
            );
            assert_eq!(combined, whole, "combine split at {k}");
            assert_eq!(
                crc32(crc32(0, &data[..k]), &data[k..]),
                whole,
                "chain at {k}"
            );
        }
    }
}
