// Allow dead_code: these constants will be used by inflate/mod.rs and
// inflate/fast.rs once those modules are fully implemented.
#![allow(dead_code)]

//! Pre-built fixed Huffman decode tables for DEFLATE block type 1.
//!
//! This module is a faithful port of the C `inffixed.h` header from zlib
//! v1.3.2.1. It contains two compile-time constant arrays — [`LENFIX`] (512
//! entries) and [`DISTFIX`] (32 entries) — that provide pre-computed Huffman
//! decode tables for fixed Huffman codes as defined by RFC 1951 §3.2.6.
//!
//! # Background
//!
//! When a DEFLATE stream uses block type 1 (fixed Huffman codes), the decoder
//! uses a statically defined set of Huffman codes rather than codes transmitted
//! in the stream header. Per RFC 1951 §3.2.6:
//!
//! - Literal values 0–143: 8-bit codes
//! - Literal values 144–255: 9-bit codes
//! - Literal value 256 (end-of-block): 7-bit code
//! - Length values 257–279: 7-bit codes
//! - Length values 280–287: 8-bit codes
//! - Distance codes 0–31: 5-bit codes (all equal length)
//!
//! These tables were originally generated by the `makefixed()` function in the
//! C zlib source. They are embedded here as compile-time constants to avoid the
//! runtime cost of building them on every inflate initialization.
//!
//! # Op Field Semantics
//!
//! Each [`Code`] entry's `op` field encodes the operation type:
//!
//! | `op` value | Meaning |
//! |------------|---------|
//! | `0`        | Literal byte — `val` is the output byte |
//! | `16`–`21`  | Length with extra bits — `op & 15` extra bits, `val` is base length |
//! | `16`–`29` (dist) | Distance with extra bits — `op & 15` extra bits, `val` is base distance |
//! | `32` (`0x20`) | End of block |
//! | `64` (`0x40`) | Invalid code |
//! | `96` (`0x60`) | End of block (96 = 32 + 64, used as a sentinel) |

use super::tables::Code;

// ---------------------------------------------------------------------------
// Bit-size constants for fixed Huffman table lookups
// ---------------------------------------------------------------------------

/// Number of index bits for the fixed length/literal code table.
///
/// A 9-bit root table yields 2^9 = 512 entries in [`LENFIX`]. The inflate
/// engine sets `state.lenbits = FIXLCODES_BITS` when processing a fixed
/// Huffman block (DEFLATE block type 1).
pub(crate) const FIXLCODES_BITS: u32 = 9;

/// Number of index bits for the fixed distance code table.
///
/// A 5-bit root table yields 2^5 = 32 entries in [`DISTFIX`]. The inflate
/// engine sets `state.distbits = FIXDCODES_BITS` when processing a fixed
/// Huffman block (DEFLATE block type 1).
pub(crate) const FIXDCODES_BITS: u32 = 5;

// ---------------------------------------------------------------------------
// LENFIX — Pre-built fixed Huffman decode table for length/literal codes
// ---------------------------------------------------------------------------

/// Pre-built fixed Huffman decode table for length/literal codes.
///
/// This table contains 512 [`Code`] entries (indexed by the low 9 bits of the
/// bit accumulator, i.e. `1 << FIXLCODES_BITS`). It was generated by the
/// `makefixed()` function and encodes the fixed Huffman code assignment
/// specified in RFC 1951 §3.2.6.
///
/// The table is a single-level lookup: all fixed literal/length codes are at
/// most 9 bits, so no sub-tables are needed.
///
/// # Layout
///
/// Each entry maps a 9-bit reversed Huffman code to its decoded symbol:
///
/// - `op == 0`: literal byte, `val` is the byte value (0–255)
/// - `op & 16 != 0`: length code, `op & 15` extra bits, `val` is base length
/// - `op & 32 != 0`: end-of-block (literal 256)
/// - `op & 64 != 0`: invalid code
#[rustfmt::skip]
pub(crate) const LENFIX: [Code; 512] = [
    Code::new(96, 7, 0), Code::new(0, 8, 80), Code::new(0, 8, 16), Code::new(20, 8, 115), Code::new(18, 7, 31), Code::new(0, 8, 112), Code::new(0, 8, 48),
    Code::new(0, 9, 192), Code::new(16, 7, 10), Code::new(0, 8, 96), Code::new(0, 8, 32), Code::new(0, 9, 160), Code::new(0, 8, 0), Code::new(0, 8, 128),
    Code::new(0, 8, 64), Code::new(0, 9, 224), Code::new(16, 7, 6), Code::new(0, 8, 88), Code::new(0, 8, 24), Code::new(0, 9, 144), Code::new(19, 7, 59),
    Code::new(0, 8, 120), Code::new(0, 8, 56), Code::new(0, 9, 208), Code::new(17, 7, 17), Code::new(0, 8, 104), Code::new(0, 8, 40), Code::new(0, 9, 176),
    Code::new(0, 8, 8), Code::new(0, 8, 136), Code::new(0, 8, 72), Code::new(0, 9, 240), Code::new(16, 7, 4), Code::new(0, 8, 84), Code::new(0, 8, 20),
    Code::new(21, 8, 227), Code::new(19, 7, 43), Code::new(0, 8, 116), Code::new(0, 8, 52), Code::new(0, 9, 200), Code::new(17, 7, 13), Code::new(0, 8, 100),
    Code::new(0, 8, 36), Code::new(0, 9, 168), Code::new(0, 8, 4), Code::new(0, 8, 132), Code::new(0, 8, 68), Code::new(0, 9, 232), Code::new(16, 7, 8),
    Code::new(0, 8, 92), Code::new(0, 8, 28), Code::new(0, 9, 152), Code::new(20, 7, 83), Code::new(0, 8, 124), Code::new(0, 8, 60), Code::new(0, 9, 216),
    Code::new(18, 7, 23), Code::new(0, 8, 108), Code::new(0, 8, 44), Code::new(0, 9, 184), Code::new(0, 8, 12), Code::new(0, 8, 140), Code::new(0, 8, 76),
    Code::new(0, 9, 248), Code::new(16, 7, 3), Code::new(0, 8, 82), Code::new(0, 8, 18), Code::new(21, 8, 163), Code::new(19, 7, 35), Code::new(0, 8, 114),
    Code::new(0, 8, 50), Code::new(0, 9, 196), Code::new(17, 7, 11), Code::new(0, 8, 98), Code::new(0, 8, 34), Code::new(0, 9, 164), Code::new(0, 8, 2),
    Code::new(0, 8, 130), Code::new(0, 8, 66), Code::new(0, 9, 228), Code::new(16, 7, 7), Code::new(0, 8, 90), Code::new(0, 8, 26), Code::new(0, 9, 148),
    Code::new(20, 7, 67), Code::new(0, 8, 122), Code::new(0, 8, 58), Code::new(0, 9, 212), Code::new(18, 7, 19), Code::new(0, 8, 106), Code::new(0, 8, 42),
    Code::new(0, 9, 180), Code::new(0, 8, 10), Code::new(0, 8, 138), Code::new(0, 8, 74), Code::new(0, 9, 244), Code::new(16, 7, 5), Code::new(0, 8, 86),
    Code::new(0, 8, 22), Code::new(64, 8, 0), Code::new(19, 7, 51), Code::new(0, 8, 118), Code::new(0, 8, 54), Code::new(0, 9, 204), Code::new(17, 7, 15),
    Code::new(0, 8, 102), Code::new(0, 8, 38), Code::new(0, 9, 172), Code::new(0, 8, 6), Code::new(0, 8, 134), Code::new(0, 8, 70), Code::new(0, 9, 236),
    Code::new(16, 7, 9), Code::new(0, 8, 94), Code::new(0, 8, 30), Code::new(0, 9, 156), Code::new(20, 7, 99), Code::new(0, 8, 126), Code::new(0, 8, 62),
    Code::new(0, 9, 220), Code::new(18, 7, 27), Code::new(0, 8, 110), Code::new(0, 8, 46), Code::new(0, 9, 188), Code::new(0, 8, 14), Code::new(0, 8, 142),
    Code::new(0, 8, 78), Code::new(0, 9, 252), Code::new(96, 7, 0), Code::new(0, 8, 81), Code::new(0, 8, 17), Code::new(21, 8, 131), Code::new(18, 7, 31),
    Code::new(0, 8, 113), Code::new(0, 8, 49), Code::new(0, 9, 194), Code::new(16, 7, 10), Code::new(0, 8, 97), Code::new(0, 8, 33), Code::new(0, 9, 162),
    Code::new(0, 8, 1), Code::new(0, 8, 129), Code::new(0, 8, 65), Code::new(0, 9, 226), Code::new(16, 7, 6), Code::new(0, 8, 89), Code::new(0, 8, 25),
    Code::new(0, 9, 146), Code::new(19, 7, 59), Code::new(0, 8, 121), Code::new(0, 8, 57), Code::new(0, 9, 210), Code::new(17, 7, 17), Code::new(0, 8, 105),
    Code::new(0, 8, 41), Code::new(0, 9, 178), Code::new(0, 8, 9), Code::new(0, 8, 137), Code::new(0, 8, 73), Code::new(0, 9, 242), Code::new(16, 7, 4),
    Code::new(0, 8, 85), Code::new(0, 8, 21), Code::new(16, 8, 258), Code::new(19, 7, 43), Code::new(0, 8, 117), Code::new(0, 8, 53), Code::new(0, 9, 202),
    Code::new(17, 7, 13), Code::new(0, 8, 101), Code::new(0, 8, 37), Code::new(0, 9, 170), Code::new(0, 8, 5), Code::new(0, 8, 133), Code::new(0, 8, 69),
    Code::new(0, 9, 234), Code::new(16, 7, 8), Code::new(0, 8, 93), Code::new(0, 8, 29), Code::new(0, 9, 154), Code::new(20, 7, 83), Code::new(0, 8, 125),
    Code::new(0, 8, 61), Code::new(0, 9, 218), Code::new(18, 7, 23), Code::new(0, 8, 109), Code::new(0, 8, 45), Code::new(0, 9, 186), Code::new(0, 8, 13),
    Code::new(0, 8, 141), Code::new(0, 8, 77), Code::new(0, 9, 250), Code::new(16, 7, 3), Code::new(0, 8, 83), Code::new(0, 8, 19), Code::new(21, 8, 195),
    Code::new(19, 7, 35), Code::new(0, 8, 115), Code::new(0, 8, 51), Code::new(0, 9, 198), Code::new(17, 7, 11), Code::new(0, 8, 99), Code::new(0, 8, 35),
    Code::new(0, 9, 166), Code::new(0, 8, 3), Code::new(0, 8, 131), Code::new(0, 8, 67), Code::new(0, 9, 230), Code::new(16, 7, 7), Code::new(0, 8, 91),
    Code::new(0, 8, 27), Code::new(0, 9, 150), Code::new(20, 7, 67), Code::new(0, 8, 123), Code::new(0, 8, 59), Code::new(0, 9, 214), Code::new(18, 7, 19),
    Code::new(0, 8, 107), Code::new(0, 8, 43), Code::new(0, 9, 182), Code::new(0, 8, 11), Code::new(0, 8, 139), Code::new(0, 8, 75), Code::new(0, 9, 246),
    Code::new(16, 7, 5), Code::new(0, 8, 87), Code::new(0, 8, 23), Code::new(64, 8, 0), Code::new(19, 7, 51), Code::new(0, 8, 119), Code::new(0, 8, 55),
    Code::new(0, 9, 206), Code::new(17, 7, 15), Code::new(0, 8, 103), Code::new(0, 8, 39), Code::new(0, 9, 174), Code::new(0, 8, 7), Code::new(0, 8, 135),
    Code::new(0, 8, 71), Code::new(0, 9, 238), Code::new(16, 7, 9), Code::new(0, 8, 95), Code::new(0, 8, 31), Code::new(0, 9, 158), Code::new(20, 7, 99),
    Code::new(0, 8, 127), Code::new(0, 8, 63), Code::new(0, 9, 222), Code::new(18, 7, 27), Code::new(0, 8, 111), Code::new(0, 8, 47), Code::new(0, 9, 190),
    Code::new(0, 8, 15), Code::new(0, 8, 143), Code::new(0, 8, 79), Code::new(0, 9, 254), Code::new(96, 7, 0), Code::new(0, 8, 80), Code::new(0, 8, 16),
    Code::new(20, 8, 115), Code::new(18, 7, 31), Code::new(0, 8, 112), Code::new(0, 8, 48), Code::new(0, 9, 193), Code::new(16, 7, 10), Code::new(0, 8, 96),
    Code::new(0, 8, 32), Code::new(0, 9, 161), Code::new(0, 8, 0), Code::new(0, 8, 128), Code::new(0, 8, 64), Code::new(0, 9, 225), Code::new(16, 7, 6),
    Code::new(0, 8, 88), Code::new(0, 8, 24), Code::new(0, 9, 145), Code::new(19, 7, 59), Code::new(0, 8, 120), Code::new(0, 8, 56), Code::new(0, 9, 209),
    Code::new(17, 7, 17), Code::new(0, 8, 104), Code::new(0, 8, 40), Code::new(0, 9, 177), Code::new(0, 8, 8), Code::new(0, 8, 136), Code::new(0, 8, 72),
    Code::new(0, 9, 241), Code::new(16, 7, 4), Code::new(0, 8, 84), Code::new(0, 8, 20), Code::new(21, 8, 227), Code::new(19, 7, 43), Code::new(0, 8, 116),
    Code::new(0, 8, 52), Code::new(0, 9, 201), Code::new(17, 7, 13), Code::new(0, 8, 100), Code::new(0, 8, 36), Code::new(0, 9, 169), Code::new(0, 8, 4),
    Code::new(0, 8, 132), Code::new(0, 8, 68), Code::new(0, 9, 233), Code::new(16, 7, 8), Code::new(0, 8, 92), Code::new(0, 8, 28), Code::new(0, 9, 153),
    Code::new(20, 7, 83), Code::new(0, 8, 124), Code::new(0, 8, 60), Code::new(0, 9, 217), Code::new(18, 7, 23), Code::new(0, 8, 108), Code::new(0, 8, 44),
    Code::new(0, 9, 185), Code::new(0, 8, 12), Code::new(0, 8, 140), Code::new(0, 8, 76), Code::new(0, 9, 249), Code::new(16, 7, 3), Code::new(0, 8, 82),
    Code::new(0, 8, 18), Code::new(21, 8, 163), Code::new(19, 7, 35), Code::new(0, 8, 114), Code::new(0, 8, 50), Code::new(0, 9, 197), Code::new(17, 7, 11),
    Code::new(0, 8, 98), Code::new(0, 8, 34), Code::new(0, 9, 165), Code::new(0, 8, 2), Code::new(0, 8, 130), Code::new(0, 8, 66), Code::new(0, 9, 229),
    Code::new(16, 7, 7), Code::new(0, 8, 90), Code::new(0, 8, 26), Code::new(0, 9, 149), Code::new(20, 7, 67), Code::new(0, 8, 122), Code::new(0, 8, 58),
    Code::new(0, 9, 213), Code::new(18, 7, 19), Code::new(0, 8, 106), Code::new(0, 8, 42), Code::new(0, 9, 181), Code::new(0, 8, 10), Code::new(0, 8, 138),
    Code::new(0, 8, 74), Code::new(0, 9, 245), Code::new(16, 7, 5), Code::new(0, 8, 86), Code::new(0, 8, 22), Code::new(64, 8, 0), Code::new(19, 7, 51),
    Code::new(0, 8, 118), Code::new(0, 8, 54), Code::new(0, 9, 205), Code::new(17, 7, 15), Code::new(0, 8, 102), Code::new(0, 8, 38), Code::new(0, 9, 173),
    Code::new(0, 8, 6), Code::new(0, 8, 134), Code::new(0, 8, 70), Code::new(0, 9, 237), Code::new(16, 7, 9), Code::new(0, 8, 94), Code::new(0, 8, 30),
    Code::new(0, 9, 157), Code::new(20, 7, 99), Code::new(0, 8, 126), Code::new(0, 8, 62), Code::new(0, 9, 221), Code::new(18, 7, 27), Code::new(0, 8, 110),
    Code::new(0, 8, 46), Code::new(0, 9, 189), Code::new(0, 8, 14), Code::new(0, 8, 142), Code::new(0, 8, 78), Code::new(0, 9, 253), Code::new(96, 7, 0),
    Code::new(0, 8, 81), Code::new(0, 8, 17), Code::new(21, 8, 131), Code::new(18, 7, 31), Code::new(0, 8, 113), Code::new(0, 8, 49), Code::new(0, 9, 195),
    Code::new(16, 7, 10), Code::new(0, 8, 97), Code::new(0, 8, 33), Code::new(0, 9, 163), Code::new(0, 8, 1), Code::new(0, 8, 129), Code::new(0, 8, 65),
    Code::new(0, 9, 227), Code::new(16, 7, 6), Code::new(0, 8, 89), Code::new(0, 8, 25), Code::new(0, 9, 147), Code::new(19, 7, 59), Code::new(0, 8, 121),
    Code::new(0, 8, 57), Code::new(0, 9, 211), Code::new(17, 7, 17), Code::new(0, 8, 105), Code::new(0, 8, 41), Code::new(0, 9, 179), Code::new(0, 8, 9),
    Code::new(0, 8, 137), Code::new(0, 8, 73), Code::new(0, 9, 243), Code::new(16, 7, 4), Code::new(0, 8, 85), Code::new(0, 8, 21), Code::new(16, 8, 258),
    Code::new(19, 7, 43), Code::new(0, 8, 117), Code::new(0, 8, 53), Code::new(0, 9, 203), Code::new(17, 7, 13), Code::new(0, 8, 101), Code::new(0, 8, 37),
    Code::new(0, 9, 171), Code::new(0, 8, 5), Code::new(0, 8, 133), Code::new(0, 8, 69), Code::new(0, 9, 235), Code::new(16, 7, 8), Code::new(0, 8, 93),
    Code::new(0, 8, 29), Code::new(0, 9, 155), Code::new(20, 7, 83), Code::new(0, 8, 125), Code::new(0, 8, 61), Code::new(0, 9, 219), Code::new(18, 7, 23),
    Code::new(0, 8, 109), Code::new(0, 8, 45), Code::new(0, 9, 187), Code::new(0, 8, 13), Code::new(0, 8, 141), Code::new(0, 8, 77), Code::new(0, 9, 251),
    Code::new(16, 7, 3), Code::new(0, 8, 83), Code::new(0, 8, 19), Code::new(21, 8, 195), Code::new(19, 7, 35), Code::new(0, 8, 115), Code::new(0, 8, 51),
    Code::new(0, 9, 199), Code::new(17, 7, 11), Code::new(0, 8, 99), Code::new(0, 8, 35), Code::new(0, 9, 167), Code::new(0, 8, 3), Code::new(0, 8, 131),
    Code::new(0, 8, 67), Code::new(0, 9, 231), Code::new(16, 7, 7), Code::new(0, 8, 91), Code::new(0, 8, 27), Code::new(0, 9, 151), Code::new(20, 7, 67),
    Code::new(0, 8, 123), Code::new(0, 8, 59), Code::new(0, 9, 215), Code::new(18, 7, 19), Code::new(0, 8, 107), Code::new(0, 8, 43), Code::new(0, 9, 183),
    Code::new(0, 8, 11), Code::new(0, 8, 139), Code::new(0, 8, 75), Code::new(0, 9, 247), Code::new(16, 7, 5), Code::new(0, 8, 87), Code::new(0, 8, 23),
    Code::new(64, 8, 0), Code::new(19, 7, 51), Code::new(0, 8, 119), Code::new(0, 8, 55), Code::new(0, 9, 207), Code::new(17, 7, 15), Code::new(0, 8, 103),
    Code::new(0, 8, 39), Code::new(0, 9, 175), Code::new(0, 8, 7), Code::new(0, 8, 135), Code::new(0, 8, 71), Code::new(0, 9, 239), Code::new(16, 7, 9),
    Code::new(0, 8, 95), Code::new(0, 8, 31), Code::new(0, 9, 159), Code::new(20, 7, 99), Code::new(0, 8, 127), Code::new(0, 8, 63), Code::new(0, 9, 223),
    Code::new(18, 7, 27), Code::new(0, 8, 111), Code::new(0, 8, 47), Code::new(0, 9, 191), Code::new(0, 8, 15), Code::new(0, 8, 143), Code::new(0, 8, 79),
    Code::new(0, 9, 255),
];

// ---------------------------------------------------------------------------
// DISTFIX — Pre-built fixed Huffman decode table for distance codes
// ---------------------------------------------------------------------------

/// Pre-built fixed Huffman decode table for distance codes.
///
/// This table contains 32 [`Code`] entries (indexed by the low 5 bits of the
/// bit accumulator, i.e. `1 << FIXDCODES_BITS`). It was generated by the
/// `makefixed()` function and encodes the fixed Huffman distance code
/// assignment specified in RFC 1951 §3.2.6.
///
/// All 32 fixed distance codes use 5 bits. Distance codes 0–29 are valid;
/// codes 30 and 31 are marked invalid (`op == 64`).
///
/// # Layout
///
/// Each entry maps a 5-bit reversed distance code to its decoded symbol:
///
/// - `op & 16 != 0`: distance code, `op & 15` extra bits, `val` is base distance
/// - `op & 64 != 0`: invalid code (distance codes 30–31)
#[rustfmt::skip]
pub(crate) const DISTFIX: [Code; 32] = [
    Code::new(16, 5, 1), Code::new(23, 5, 257), Code::new(19, 5, 17), Code::new(27, 5, 4097),
    Code::new(17, 5, 5), Code::new(25, 5, 1025), Code::new(21, 5, 65), Code::new(29, 5, 16385),
    Code::new(16, 5, 3), Code::new(24, 5, 513), Code::new(20, 5, 33), Code::new(28, 5, 8193),
    Code::new(18, 5, 9), Code::new(26, 5, 2049), Code::new(22, 5, 129), Code::new(64, 5, 0),
    Code::new(16, 5, 2), Code::new(23, 5, 385), Code::new(19, 5, 25), Code::new(27, 5, 6145),
    Code::new(17, 5, 7), Code::new(25, 5, 1537), Code::new(21, 5, 97), Code::new(29, 5, 24577),
    Code::new(16, 5, 4), Code::new(24, 5, 769), Code::new(20, 5, 49), Code::new(28, 5, 12289),
    Code::new(18, 5, 13), Code::new(26, 5, 3073), Code::new(22, 5, 193), Code::new(64, 5, 0),
];
