//! Pre-computed fixed Huffman tables for DEFLATE block type 1.
//!
//! This module provides compile-time constant lookup tables for the DEFLATE
//! "fixed" block type (block type 1), as defined in RFC 1951 Section 3.2.6.
//! When the deflate encoder chooses fixed Huffman codes instead of dynamic
//! codes, the inflate decoder uses these pre-computed tables to avoid runtime
//! table construction.
//!
//! The tables were originally generated by the `makefixed()` function in C zlib
//! and stored in `inffixed.h`. They are equivalent to calling `inflate_table()`
//! with the fixed code lengths specified by the DEFLATE standard.
//!
//! # `op` field encoding
//!
//! Each [`Code`] entry's `op` field uses the encoding defined by
//! `inflate_table()`:
//!
//! | Bit pattern   | Decimal | Meaning                                              |
//! |---------------|---------|------------------------------------------------------|
//! | `0000_0000`   | 0       | Literal byte — `val` is the byte value               |
//! | `0000_tttt`   | 1–15    | Sub-table link — `tttt` is the number of index bits  |
//! | `0001_eeee`   | 16–31   | Length or distance — `eeee` extra bits, `val` = base |
//! | `0100_0000`   | 64      | Invalid code marker                                  |
//! | `0110_0000`   | 96      | End-of-block marker (32 + 64)                        |

use super::state::{CodeTableRef, InflateState};
use super::table::Code;

// ---------------------------------------------------------------------------
// Helper — short alias for `Code::new` to keep table lines within 100 columns
// ---------------------------------------------------------------------------

/// Shorthand constructor for [`Code`] values used in const table initializers.
///
/// Equivalent to `Code::new(op, bits, val)` but reduces line length when
/// constructing the 512-entry `LENFIX` and 32-entry `DISTFIX` tables.
#[allow(non_snake_case)]
const fn C(op: u8, bits: u8, val: u16) -> Code {
    Code::new(op, bits, val)
}

// ---------------------------------------------------------------------------
// LENFIX — Fixed length/literal code table (512 entries, 9-bit root)
// ---------------------------------------------------------------------------

/// Pre-computed fixed Huffman table for length/literal codes.
///
/// Contains 512 entries indexed by 9 bits of input (the root table size for
/// fixed literal/length codes). Generated by `makefixed()` — equivalent to
/// `inflate_table(LENS, ...)` with the fixed literal/length code lengths
/// defined in RFC 1951 Section 3.2.6:
///
/// - Codes 0–143:   8-bit codes (literals 0–143)
/// - Codes 144–255: 9-bit codes (literals 144–255)
/// - Codes 256–279: 7-bit codes (end-of-block + lengths)
/// - Codes 280–287: 8-bit codes (lengths)
///
/// The table encodes these into lookup entries where:
/// - `op = 0`: literal byte, `val` is the byte value
/// - `op = 96`: end-of-block (code 256)
/// - `op = 16..31`: length code, `op & 15` extra bits, `val` is base length
/// - `op = 64`: invalid code
pub(crate) const LENFIX: [Code; 512] = [
    // Row  0 — indices   0..  6
    C(96, 7, 0),
    C(0, 8, 80),
    C(0, 8, 16),
    C(20, 8, 115),
    C(18, 7, 31),
    C(0, 8, 112),
    C(0, 8, 48),
    // Row  1 — indices   7.. 13
    C(0, 9, 192),
    C(16, 7, 10),
    C(0, 8, 96),
    C(0, 8, 32),
    C(0, 9, 160),
    C(0, 8, 0),
    C(0, 8, 128),
    // Row  2 — indices  14.. 20
    C(0, 8, 64),
    C(0, 9, 224),
    C(16, 7, 6),
    C(0, 8, 88),
    C(0, 8, 24),
    C(0, 9, 144),
    C(19, 7, 59),
    // Row  3 — indices  21.. 27
    C(0, 8, 120),
    C(0, 8, 56),
    C(0, 9, 208),
    C(17, 7, 17),
    C(0, 8, 104),
    C(0, 8, 40),
    C(0, 9, 176),
    // Row  4 — indices  28.. 34
    C(0, 8, 8),
    C(0, 8, 136),
    C(0, 8, 72),
    C(0, 9, 240),
    C(16, 7, 4),
    C(0, 8, 84),
    C(0, 8, 20),
    // Row  5 — indices  35.. 41
    C(21, 8, 227),
    C(19, 7, 43),
    C(0, 8, 116),
    C(0, 8, 52),
    C(0, 9, 200),
    C(17, 7, 13),
    C(0, 8, 100),
    // Row  6 — indices  42.. 48
    C(0, 8, 36),
    C(0, 9, 168),
    C(0, 8, 4),
    C(0, 8, 132),
    C(0, 8, 68),
    C(0, 9, 232),
    C(16, 7, 8),
    // Row  7 — indices  49.. 55
    C(0, 8, 92),
    C(0, 8, 28),
    C(0, 9, 152),
    C(20, 7, 83),
    C(0, 8, 124),
    C(0, 8, 60),
    C(0, 9, 216),
    // Row  8 — indices  56.. 62
    C(18, 7, 23),
    C(0, 8, 108),
    C(0, 8, 44),
    C(0, 9, 184),
    C(0, 8, 12),
    C(0, 8, 140),
    C(0, 8, 76),
    // Row  9 — indices  63.. 69
    C(0, 9, 248),
    C(16, 7, 3),
    C(0, 8, 82),
    C(0, 8, 18),
    C(21, 8, 163),
    C(19, 7, 35),
    C(0, 8, 114),
    // Row 10 — indices  70.. 76
    C(0, 8, 50),
    C(0, 9, 196),
    C(17, 7, 11),
    C(0, 8, 98),
    C(0, 8, 34),
    C(0, 9, 164),
    C(0, 8, 2),
    // Row 11 — indices  77.. 83
    C(0, 8, 130),
    C(0, 8, 66),
    C(0, 9, 228),
    C(16, 7, 7),
    C(0, 8, 90),
    C(0, 8, 26),
    C(0, 9, 148),
    // Row 12 — indices  84.. 90
    C(20, 7, 67),
    C(0, 8, 122),
    C(0, 8, 58),
    C(0, 9, 212),
    C(18, 7, 19),
    C(0, 8, 106),
    C(0, 8, 42),
    // Row 13 — indices  91.. 97
    C(0, 9, 180),
    C(0, 8, 10),
    C(0, 8, 138),
    C(0, 8, 74),
    C(0, 9, 244),
    C(16, 7, 5),
    C(0, 8, 86),
    // Row 14 — indices  98..104
    C(0, 8, 22),
    C(64, 8, 0),
    C(19, 7, 51),
    C(0, 8, 118),
    C(0, 8, 54),
    C(0, 9, 204),
    C(17, 7, 15),
    // Row 15 — indices 105..111
    C(0, 8, 102),
    C(0, 8, 38),
    C(0, 9, 172),
    C(0, 8, 6),
    C(0, 8, 134),
    C(0, 8, 70),
    C(0, 9, 236),
    // Row 16 — indices 112..118
    C(16, 7, 9),
    C(0, 8, 94),
    C(0, 8, 30),
    C(0, 9, 156),
    C(20, 7, 99),
    C(0, 8, 126),
    C(0, 8, 62),
    // Row 17 — indices 119..125
    C(0, 9, 220),
    C(18, 7, 27),
    C(0, 8, 110),
    C(0, 8, 46),
    C(0, 9, 188),
    C(0, 8, 14),
    C(0, 8, 142),
    // Row 18 — indices 126..132  (second half begins at 128)
    C(0, 8, 78),
    C(0, 9, 252),
    C(96, 7, 0),
    C(0, 8, 81),
    C(0, 8, 17),
    C(21, 8, 131),
    C(18, 7, 31),
    // Row 19 — indices 133..139
    C(0, 8, 113),
    C(0, 8, 49),
    C(0, 9, 194),
    C(16, 7, 10),
    C(0, 8, 97),
    C(0, 8, 33),
    C(0, 9, 162),
    // Row 20 — indices 140..146
    C(0, 8, 1),
    C(0, 8, 129),
    C(0, 8, 65),
    C(0, 9, 226),
    C(16, 7, 6),
    C(0, 8, 89),
    C(0, 8, 25),
    // Row 21 — indices 147..153
    C(0, 9, 146),
    C(19, 7, 59),
    C(0, 8, 121),
    C(0, 8, 57),
    C(0, 9, 210),
    C(17, 7, 17),
    C(0, 8, 105),
    // Row 22 — indices 154..160
    C(0, 8, 41),
    C(0, 9, 178),
    C(0, 8, 9),
    C(0, 8, 137),
    C(0, 8, 73),
    C(0, 9, 242),
    C(16, 7, 4),
    // Row 23 — indices 161..167
    C(0, 8, 85),
    C(0, 8, 21),
    C(16, 8, 258),
    C(19, 7, 43),
    C(0, 8, 117),
    C(0, 8, 53),
    C(0, 9, 202),
    // Row 24 — indices 168..174
    C(17, 7, 13),
    C(0, 8, 101),
    C(0, 8, 37),
    C(0, 9, 170),
    C(0, 8, 5),
    C(0, 8, 133),
    C(0, 8, 69),
    // Row 25 — indices 175..181
    C(0, 9, 234),
    C(16, 7, 8),
    C(0, 8, 93),
    C(0, 8, 29),
    C(0, 9, 154),
    C(20, 7, 83),
    C(0, 8, 125),
    // Row 26 — indices 182..188
    C(0, 8, 61),
    C(0, 9, 218),
    C(18, 7, 23),
    C(0, 8, 109),
    C(0, 8, 45),
    C(0, 9, 186),
    C(0, 8, 13),
    // Row 27 — indices 189..195
    C(0, 8, 141),
    C(0, 8, 77),
    C(0, 9, 250),
    C(16, 7, 3),
    C(0, 8, 83),
    C(0, 8, 19),
    C(21, 8, 195),
    // Row 28 — indices 196..202
    C(19, 7, 35),
    C(0, 8, 115),
    C(0, 8, 51),
    C(0, 9, 198),
    C(17, 7, 11),
    C(0, 8, 99),
    C(0, 8, 35),
    // Row 29 — indices 203..209
    C(0, 9, 166),
    C(0, 8, 3),
    C(0, 8, 131),
    C(0, 8, 67),
    C(0, 9, 230),
    C(16, 7, 7),
    C(0, 8, 91),
    // Row 30 — indices 210..216
    C(0, 8, 27),
    C(0, 9, 150),
    C(20, 7, 67),
    C(0, 8, 123),
    C(0, 8, 59),
    C(0, 9, 214),
    C(18, 7, 19),
    // Row 31 — indices 217..223
    C(0, 8, 107),
    C(0, 8, 43),
    C(0, 9, 182),
    C(0, 8, 11),
    C(0, 8, 139),
    C(0, 8, 75),
    C(0, 9, 246),
    // Row 32 — indices 224..230
    C(16, 7, 5),
    C(0, 8, 87),
    C(0, 8, 23),
    C(64, 8, 0),
    C(19, 7, 51),
    C(0, 8, 119),
    C(0, 8, 55),
    // Row 33 — indices 231..237
    C(0, 9, 206),
    C(17, 7, 15),
    C(0, 8, 103),
    C(0, 8, 39),
    C(0, 9, 174),
    C(0, 8, 7),
    C(0, 8, 135),
    // Row 34 — indices 238..244
    C(0, 8, 71),
    C(0, 9, 238),
    C(16, 7, 9),
    C(0, 8, 95),
    C(0, 8, 31),
    C(0, 9, 158),
    C(20, 7, 99),
    // Row 35 — indices 245..251
    C(0, 8, 127),
    C(0, 8, 63),
    C(0, 9, 222),
    C(18, 7, 27),
    C(0, 8, 111),
    C(0, 8, 47),
    C(0, 9, 190),
    // Row 36 — indices 252..258  (third quarter begins at 256)
    C(0, 8, 15),
    C(0, 8, 143),
    C(0, 8, 79),
    C(0, 9, 254),
    C(96, 7, 0),
    C(0, 8, 80),
    C(0, 8, 16),
    // Row 37 — indices 259..265
    C(20, 8, 115),
    C(18, 7, 31),
    C(0, 8, 112),
    C(0, 8, 48),
    C(0, 9, 193),
    C(16, 7, 10),
    C(0, 8, 96),
    // Row 38 — indices 266..272
    C(0, 8, 32),
    C(0, 9, 161),
    C(0, 8, 0),
    C(0, 8, 128),
    C(0, 8, 64),
    C(0, 9, 225),
    C(16, 7, 6),
    // Row 39 — indices 273..279
    C(0, 8, 88),
    C(0, 8, 24),
    C(0, 9, 145),
    C(19, 7, 59),
    C(0, 8, 120),
    C(0, 8, 56),
    C(0, 9, 209),
    // Row 40 — indices 280..286
    C(17, 7, 17),
    C(0, 8, 104),
    C(0, 8, 40),
    C(0, 9, 177),
    C(0, 8, 8),
    C(0, 8, 136),
    C(0, 8, 72),
    // Row 41 — indices 287..293
    C(0, 9, 241),
    C(16, 7, 4),
    C(0, 8, 84),
    C(0, 8, 20),
    C(21, 8, 227),
    C(19, 7, 43),
    C(0, 8, 116),
    // Row 42 — indices 294..300
    C(0, 8, 52),
    C(0, 9, 201),
    C(17, 7, 13),
    C(0, 8, 100),
    C(0, 8, 36),
    C(0, 9, 169),
    C(0, 8, 4),
    // Row 43 — indices 301..307
    C(0, 8, 132),
    C(0, 8, 68),
    C(0, 9, 233),
    C(16, 7, 8),
    C(0, 8, 92),
    C(0, 8, 28),
    C(0, 9, 153),
    // Row 44 — indices 308..314
    C(20, 7, 83),
    C(0, 8, 124),
    C(0, 8, 60),
    C(0, 9, 217),
    C(18, 7, 23),
    C(0, 8, 108),
    C(0, 8, 44),
    // Row 45 — indices 315..321
    C(0, 9, 185),
    C(0, 8, 12),
    C(0, 8, 140),
    C(0, 8, 76),
    C(0, 9, 249),
    C(16, 7, 3),
    C(0, 8, 82),
    // Row 46 — indices 322..328
    C(0, 8, 18),
    C(21, 8, 163),
    C(19, 7, 35),
    C(0, 8, 114),
    C(0, 8, 50),
    C(0, 9, 197),
    C(17, 7, 11),
    // Row 47 — indices 329..335
    C(0, 8, 98),
    C(0, 8, 34),
    C(0, 9, 165),
    C(0, 8, 2),
    C(0, 8, 130),
    C(0, 8, 66),
    C(0, 9, 229),
    // Row 48 — indices 336..342
    C(16, 7, 7),
    C(0, 8, 90),
    C(0, 8, 26),
    C(0, 9, 149),
    C(20, 7, 67),
    C(0, 8, 122),
    C(0, 8, 58),
    // Row 49 — indices 343..349
    C(0, 9, 213),
    C(18, 7, 19),
    C(0, 8, 106),
    C(0, 8, 42),
    C(0, 9, 181),
    C(0, 8, 10),
    C(0, 8, 138),
    // Row 50 — indices 350..356
    C(0, 8, 74),
    C(0, 9, 245),
    C(16, 7, 5),
    C(0, 8, 86),
    C(0, 8, 22),
    C(64, 8, 0),
    C(19, 7, 51),
    // Row 51 — indices 357..363
    C(0, 8, 118),
    C(0, 8, 54),
    C(0, 9, 205),
    C(17, 7, 15),
    C(0, 8, 102),
    C(0, 8, 38),
    C(0, 9, 173),
    // Row 52 — indices 364..370
    C(0, 8, 6),
    C(0, 8, 134),
    C(0, 8, 70),
    C(0, 9, 237),
    C(16, 7, 9),
    C(0, 8, 94),
    C(0, 8, 30),
    // Row 53 — indices 371..377
    C(0, 9, 157),
    C(20, 7, 99),
    C(0, 8, 126),
    C(0, 8, 62),
    C(0, 9, 221),
    C(18, 7, 27),
    C(0, 8, 110),
    // Row 54 — indices 378..384  (fourth quarter begins at 384)
    C(0, 8, 46),
    C(0, 9, 189),
    C(0, 8, 14),
    C(0, 8, 142),
    C(0, 8, 78),
    C(0, 9, 253),
    C(96, 7, 0),
    // Row 55 — indices 385..391
    C(0, 8, 81),
    C(0, 8, 17),
    C(21, 8, 131),
    C(18, 7, 31),
    C(0, 8, 113),
    C(0, 8, 49),
    C(0, 9, 195),
    // Row 56 — indices 392..398
    C(16, 7, 10),
    C(0, 8, 97),
    C(0, 8, 33),
    C(0, 9, 163),
    C(0, 8, 1),
    C(0, 8, 129),
    C(0, 8, 65),
    // Row 57 — indices 399..405
    C(0, 9, 227),
    C(16, 7, 6),
    C(0, 8, 89),
    C(0, 8, 25),
    C(0, 9, 147),
    C(19, 7, 59),
    C(0, 8, 121),
    // Row 58 — indices 406..412
    C(0, 8, 57),
    C(0, 9, 211),
    C(17, 7, 17),
    C(0, 8, 105),
    C(0, 8, 41),
    C(0, 9, 179),
    C(0, 8, 9),
    // Row 59 — indices 413..419
    C(0, 8, 137),
    C(0, 8, 73),
    C(0, 9, 243),
    C(16, 7, 4),
    C(0, 8, 85),
    C(0, 8, 21),
    C(16, 8, 258),
    // Row 60 — indices 420..426
    C(19, 7, 43),
    C(0, 8, 117),
    C(0, 8, 53),
    C(0, 9, 203),
    C(17, 7, 13),
    C(0, 8, 101),
    C(0, 8, 37),
    // Row 61 — indices 427..433
    C(0, 9, 171),
    C(0, 8, 5),
    C(0, 8, 133),
    C(0, 8, 69),
    C(0, 9, 235),
    C(16, 7, 8),
    C(0, 8, 93),
    // Row 62 — indices 434..440
    C(0, 8, 29),
    C(0, 9, 155),
    C(20, 7, 83),
    C(0, 8, 125),
    C(0, 8, 61),
    C(0, 9, 219),
    C(18, 7, 23),
    // Row 63 — indices 441..447
    C(0, 8, 109),
    C(0, 8, 45),
    C(0, 9, 187),
    C(0, 8, 13),
    C(0, 8, 141),
    C(0, 8, 77),
    C(0, 9, 251),
    // Row 64 — indices 448..454
    C(16, 7, 3),
    C(0, 8, 83),
    C(0, 8, 19),
    C(21, 8, 195),
    C(19, 7, 35),
    C(0, 8, 115),
    C(0, 8, 51),
    // Row 65 — indices 455..461
    C(0, 9, 199),
    C(17, 7, 11),
    C(0, 8, 99),
    C(0, 8, 35),
    C(0, 9, 167),
    C(0, 8, 3),
    C(0, 8, 131),
    // Row 66 — indices 462..468
    C(0, 8, 67),
    C(0, 9, 231),
    C(16, 7, 7),
    C(0, 8, 91),
    C(0, 8, 27),
    C(0, 9, 151),
    C(20, 7, 67),
    // Row 67 — indices 469..475
    C(0, 8, 123),
    C(0, 8, 59),
    C(0, 9, 215),
    C(18, 7, 19),
    C(0, 8, 107),
    C(0, 8, 43),
    C(0, 9, 183),
    // Row 68 — indices 476..482
    C(0, 8, 11),
    C(0, 8, 139),
    C(0, 8, 75),
    C(0, 9, 247),
    C(16, 7, 5),
    C(0, 8, 87),
    C(0, 8, 23),
    // Row 69 — indices 483..489
    C(64, 8, 0),
    C(19, 7, 51),
    C(0, 8, 119),
    C(0, 8, 55),
    C(0, 9, 207),
    C(17, 7, 15),
    C(0, 8, 103),
    // Row 70 — indices 490..496
    C(0, 8, 39),
    C(0, 9, 175),
    C(0, 8, 7),
    C(0, 8, 135),
    C(0, 8, 71),
    C(0, 9, 239),
    C(16, 7, 9),
    // Row 71 — indices 497..503
    C(0, 8, 95),
    C(0, 8, 31),
    C(0, 9, 159),
    C(20, 7, 99),
    C(0, 8, 127),
    C(0, 8, 63),
    C(0, 9, 223),
    // Row 72 — indices 504..510
    C(18, 7, 27),
    C(0, 8, 111),
    C(0, 8, 47),
    C(0, 9, 191),
    C(0, 8, 15),
    C(0, 8, 143),
    C(0, 8, 79),
    // Row 73 — index  511
    C(0, 9, 255),
];

// Compile-time verification of table dimensions.
const _: () = assert!(LENFIX.len() == 512);

// ---------------------------------------------------------------------------
// DISTFIX — Fixed distance code table (32 entries, 5-bit root)
// ---------------------------------------------------------------------------

/// Pre-computed fixed Huffman table for distance codes.
///
/// Contains 32 entries indexed by 5 bits of input (the root table size for
/// fixed distance codes). Generated by `makefixed()` — equivalent to
/// `inflate_table(DISTS, ...)` with the fixed distance code lengths (all 5
/// bits for codes 0–29, unused for codes 30–31) per RFC 1951 Section 3.2.6.
///
/// Each entry encodes a base backward distance and extra-bit count:
/// - `op = 16..29`: distance code, `op & 15` extra bits, `val` is base distance
/// - `op = 64`: invalid code (codes 30 and 31)
pub(crate) const DISTFIX: [Code; 32] = [
    C(16, 5, 1),
    C(23, 5, 257),
    C(19, 5, 17),
    C(27, 5, 4097),
    C(17, 5, 5),
    C(25, 5, 1025),
    C(21, 5, 65),
    C(29, 5, 16385),
    C(16, 5, 3),
    C(24, 5, 513),
    C(20, 5, 33),
    C(28, 5, 8193),
    C(18, 5, 9),
    C(26, 5, 2049),
    C(22, 5, 129),
    C(64, 5, 0),
    C(16, 5, 2),
    C(23, 5, 385),
    C(19, 5, 25),
    C(27, 5, 6145),
    C(17, 5, 7),
    C(25, 5, 1537),
    C(21, 5, 97),
    C(29, 5, 24577),
    C(16, 5, 4),
    C(24, 5, 769),
    C(20, 5, 49),
    C(28, 5, 12289),
    C(18, 5, 13),
    C(26, 5, 3073),
    C(22, 5, 193),
    C(64, 5, 0),
];

// Compile-time verification of table dimensions.
const _: () = assert!(DISTFIX.len() == 32);

// ---------------------------------------------------------------------------
// inflate_fixed — configure state for fixed Huffman block decoding
// ---------------------------------------------------------------------------

/// Set the inflate state to use the pre-computed fixed Huffman code tables.
///
/// Called when a fixed block (DEFLATE block type 1) is encountered during
/// decompression. This function configures the inflate state's code table
/// references to point to the compile-time constant [`LENFIX`] and
/// [`DISTFIX`] tables, and sets the corresponding root table bit counts.
///
/// Ports the C `inflate_fixed()` function from `inftrees.c` line 64, which
/// is invoked from `inflate.c` line 727 in the `TYPEDO` state when the
/// block type field equals 1.
///
/// After this call:
/// - `state.lencode` references `LENFIX` (512 entries)
/// - `state.lenbits` = 9 (9-bit root table for length/literal codes)
/// - `state.distcode` references `DISTFIX` (32 entries)
/// - `state.distbits` = 5 (5-bit root table for distance codes)
pub(crate) fn inflate_fixed(state: &mut InflateState) {
    state.lencode = CodeTableRef::Fixed(&LENFIX);
    state.lenbits = 9;
    state.distcode = CodeTableRef::Fixed(&DISTFIX);
    state.distbits = 5;
}

// ---------------------------------------------------------------------------
// Compile-time spot-check assertions
// ---------------------------------------------------------------------------

// Verify a selection of entries match the canonical inffixed.h values.
// These are evaluated at compile time and produce zero runtime cost.

// LENFIX[0] = {96, 7, 0} — end-of-block
const _: () = assert!(LENFIX[0].op == 96 && LENFIX[0].bits == 7 && LENFIX[0].val == 0);
// LENFIX[1] = {0, 8, 80} — literal 80
const _: () = assert!(LENFIX[1].op == 0 && LENFIX[1].bits == 8 && LENFIX[1].val == 80);
// LENFIX[255] = {0, 9, 254} — literal 254 (9-bit code)
const _: () = assert!(LENFIX[255].op == 0 && LENFIX[255].bits == 9 && LENFIX[255].val == 254);
// LENFIX[511] = {0, 9, 255} — literal 255 (last entry)
const _: () = assert!(LENFIX[511].op == 0 && LENFIX[511].bits == 9 && LENFIX[511].val == 255);
// DISTFIX[0] = {16, 5, 1} — distance 1
const _: () = assert!(DISTFIX[0].op == 16 && DISTFIX[0].bits == 5 && DISTFIX[0].val == 1);
// DISTFIX[15] = {64, 5, 0} — invalid code
const _: () = assert!(DISTFIX[15].op == 64 && DISTFIX[15].bits == 5 && DISTFIX[15].val == 0);
// DISTFIX[31] = {64, 5, 0} — invalid code (last entry)
const _: () = assert!(DISTFIX[31].op == 64 && DISTFIX[31].bits == 5 && DISTFIX[31].val == 0);

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::super::state::{CodeTableRef, InflateState};
    use super::*;

    #[test]
    fn lenfix_has_512_entries() {
        assert_eq!(LENFIX.len(), 512);
    }

    #[test]
    fn distfix_has_32_entries() {
        assert_eq!(DISTFIX.len(), 32);
    }

    #[test]
    fn lenfix_spot_checks() {
        // LENFIX[0] = end-of-block
        assert_eq!((LENFIX[0].op, LENFIX[0].bits, LENFIX[0].val), (96, 7, 0));
        // LENFIX[1] = literal 80
        assert_eq!((LENFIX[1].op, LENFIX[1].bits, LENFIX[1].val), (0, 8, 80));
        // LENFIX[128] = second-half end-of-block
        assert_eq!(
            (LENFIX[128].op, LENFIX[128].bits, LENFIX[128].val),
            (96, 7, 0)
        );
        // LENFIX[255] = literal 254 (9-bit)
        assert_eq!(
            (LENFIX[255].op, LENFIX[255].bits, LENFIX[255].val),
            (0, 9, 254)
        );
        // LENFIX[511] = literal 255 (last)
        assert_eq!(
            (LENFIX[511].op, LENFIX[511].bits, LENFIX[511].val),
            (0, 9, 255)
        );
    }

    #[test]
    fn distfix_spot_checks() {
        // DISTFIX[0] = distance 1
        assert_eq!((DISTFIX[0].op, DISTFIX[0].bits, DISTFIX[0].val), (16, 5, 1));
        // DISTFIX[15] = invalid
        assert_eq!(
            (DISTFIX[15].op, DISTFIX[15].bits, DISTFIX[15].val),
            (64, 5, 0)
        );
        // DISTFIX[23] = distance 24577 (largest)
        assert_eq!(
            (DISTFIX[23].op, DISTFIX[23].bits, DISTFIX[23].val),
            (29, 5, 24577)
        );
        // DISTFIX[31] = invalid (last)
        assert_eq!(
            (DISTFIX[31].op, DISTFIX[31].bits, DISTFIX[31].val),
            (64, 5, 0)
        );
    }

    #[test]
    fn inflate_fixed_sets_state_correctly() {
        let mut state = InflateState::new();
        inflate_fixed(&mut state);

        assert_eq!(state.lenbits, 9);
        assert_eq!(state.distbits, 5);

        match state.lencode {
            CodeTableRef::Fixed(table) => {
                assert_eq!(table.len(), 512);
                assert_eq!(table[0].op, 96);
            }
            CodeTableRef::Dynamic(_) => panic!("Expected Fixed lencode"),
        }

        match state.distcode {
            CodeTableRef::Fixed(table) => {
                assert_eq!(table.len(), 32);
                assert_eq!(table[0].op, 16);
            }
            CodeTableRef::Dynamic(_) => panic!("Expected Fixed distcode"),
        }
    }

    #[test]
    fn inflate_fixed_enables_len_code_lookup() {
        let mut state = InflateState::new();
        inflate_fixed(&mut state);

        let code = state.len_code(0);
        assert_eq!((code.op, code.bits, code.val), (96, 7, 0));

        let code = state.len_code(1);
        assert_eq!((code.op, code.bits, code.val), (0, 8, 80));
    }

    #[test]
    fn inflate_fixed_enables_dist_code_lookup() {
        let mut state = InflateState::new();
        inflate_fixed(&mut state);

        let code = state.dist_code(0);
        assert_eq!((code.op, code.bits, code.val), (16, 5, 1));
    }

    #[test]
    fn lenfix_bits_values_are_valid() {
        for (i, code) in LENFIX.iter().enumerate() {
            assert!(
                code.bits == 7 || code.bits == 8 || code.bits == 9,
                "LENFIX[{i}].bits = {} (expected 7, 8, or 9)",
                code.bits
            );
        }
    }

    #[test]
    fn distfix_all_5_bits() {
        for (i, code) in DISTFIX.iter().enumerate() {
            assert_eq!(
                code.bits, 5,
                "DISTFIX[{i}].bits = {} (expected 5)",
                code.bits
            );
        }
    }

    #[test]
    fn lenfix_eob_count() {
        let eob_count = LENFIX.iter().filter(|c| c.op == 96).count();
        assert_eq!(eob_count, 4, "Expected 4 end-of-block markers");
        assert_eq!(LENFIX[0].op, 96);
        assert_eq!(LENFIX[128].op, 96);
        assert_eq!(LENFIX[256].op, 96);
        assert_eq!(LENFIX[384].op, 96);
    }

    #[test]
    fn lenfix_invalid_code_count() {
        let count = LENFIX.iter().filter(|c| c.op == 64).count();
        assert_eq!(count, 4, "Expected 4 invalid code markers in LENFIX");
    }

    #[test]
    fn distfix_invalid_code_count() {
        let count = DISTFIX.iter().filter(|c| c.op == 64).count();
        assert_eq!(count, 2, "Expected 2 invalid code markers in DISTFIX");
    }
}
