/* zlib.h -- interface of the 'zlib' general purpose compression library
   Auto-generated C ABI header for the Rust `libz-rs-sys` drop-in.

   Copyright (C) 1995-2026 Jean-loup Gailly and Mark Adler

   This software is provided 'as-is', without any express or implied
   warranty.  In no event will the authors be held liable for any damages
   arising from the use of this software. Permission is granted to anyone to
   use this software for any purpose, including commercial applications, and
   to alter it and redistribute it freely, subject to the restrictions of the
   zlib license. See the LICENSE file distributed with this crate.
*/

#ifndef ZLIB_RS_H
#define ZLIB_RS_H

/* DO NOT EDIT: auto-generated by cbindgen from the libz-rs-sys crate. Mirrors the canonical zlib.h C ABI. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>
#include <stdarg.h>
#include <sys/types.h>

/* ----- Items cbindgen cannot synthesize from #[no_mangle] functions ----- */
/* Library version, mirrored byte-for-byte from canonical zlib.h.           */
#define ZLIB_VERSION "1.3.2.1-motley"
#define ZLIB_VERNUM 0x1321
#define ZLIB_VER_MAJOR 1
#define ZLIB_VER_MINOR 3
#define ZLIB_VER_REVISION 2
#define ZLIB_VER_SUBREVISION 1

/* For compatibility with versions < 1.0.2 */
#define zlib_version zlibVersion()

/* Convenience init macros: check the zlib version and the compiler's view of
   z_stream, forwarding to the underscore entry points. */
#define deflateInit(strm, level) \
        deflateInit_((strm), (level), ZLIB_VERSION, (int)sizeof(z_stream))
#define inflateInit(strm) \
        inflateInit_((strm), ZLIB_VERSION, (int)sizeof(z_stream))
#define deflateInit2(strm, level, method, windowBits, memLevel, strategy) \
        deflateInit2_((strm),(level),(method),(windowBits),(memLevel),\
                      (strategy), ZLIB_VERSION, (int)sizeof(z_stream))
#define inflateInit2(strm, windowBits) \
        inflateInit2_((strm), (windowBits), ZLIB_VERSION, \
                      (int)sizeof(z_stream))
#define inflateBackInit(strm, windowBits, window) \
        inflateBackInit_((strm), (windowBits), (window), \
                         ZLIB_VERSION, (int)sizeof(z_stream))

/* ----- Scalar type system (canonical zlib `zconf.h` spellings) ----------- */
/* These public aliases let existing zlib C consumers that use the documented
   `uLong`/`Bytef`/`uInt`/... type names compile unchanged against this drop-in
   header. cbindgen RESOLVES the transparent `pub type` aliases in `zstream.rs`
   (`Bytef = u8`, `uLong = c_ulong`, ...) down to their underlying C types
   (`uint8_t`, `unsigned long`, `void *`, `size_t`, `off_t`) in the prototypes
   below, so these typedefs are purely additive and ABI-identical to that
   resolution. `z_crc_t` and `z_off64_t` are emitted by cbindgen itself (they
   alias fixed-width Rust primitives) and are intentionally NOT redefined here. */
typedef unsigned char Byte;
typedef Byte Bytef;
typedef unsigned int uInt;
typedef uInt uIntf;
typedef unsigned long uLong;
typedef uLong uLongf;
typedef void *voidp;
typedef const void *voidpc;
typedef void *voidpf;
typedef size_t z_size_t;
typedef off_t z_off_t;

/* ----- Public Z_* constants (mirrored byte-for-byte from canonical zlib.h) - */
/* These are modeled in `src/lib.rs` as `pub const` whose initializers are enum
   methods (`Flush::NoFlush.as_i32()`, ...) and cross-crate paths
   (`zlib_rs::constants::Z_DEFLATED`) that cbindgen CANNOT const-evaluate (it
   does not run `const fn`s, and `[parse] parse_deps = false` hides the core
   crate). They are therefore injected here as `#define`s (matching zlib's
   constant style) and suppressed from cbindgen emission via `[export].exclude`
   so no dangling/duplicate definition is produced. Values are verbatim from the
   canonical root `zlib.h` (the REFERENCE ABI contract). */
/* Allowed flush values. */
#define Z_NO_FLUSH      0
#define Z_PARTIAL_FLUSH 1
#define Z_SYNC_FLUSH    2
#define Z_FULL_FLUSH    3
#define Z_FINISH        4
#define Z_BLOCK         5
#define Z_TREES         6
/* Return codes for the compression/decompression functions. Negative values are
   errors, positive values are used for special but normal events. */
#define Z_OK            0
#define Z_STREAM_END    1
#define Z_NEED_DICT     2
#define Z_ERRNO        (-1)
#define Z_STREAM_ERROR (-2)
#define Z_DATA_ERROR   (-3)
#define Z_MEM_ERROR    (-4)
#define Z_BUF_ERROR    (-5)
#define Z_VERSION_ERROR (-6)
/* Compression levels. */
#define Z_NO_COMPRESSION         0
#define Z_BEST_SPEED             1
#define Z_BEST_COMPRESSION       9
#define Z_DEFAULT_COMPRESSION  (-1)
/* Compression strategies; see deflateInit2() for details. */
#define Z_FILTERED            1
#define Z_HUFFMAN_ONLY        2
#define Z_RLE                 3
#define Z_FIXED               4
#define Z_DEFAULT_STRATEGY    0
/* Possible values of the data_type field for deflate(). */
#define Z_BINARY   0
#define Z_TEXT     1
#define Z_ASCII    Z_TEXT
#define Z_UNKNOWN  2
/* The deflate compression method (the only one supported in this version). */
#define Z_DEFLATED   8
/* Null sentinel for initializing zalloc, zfree, opaque. */
#define Z_NULL  0

/* ----- gzip file-I/O API gating ------------------------------------------ */
/* The gzip file-I/O family (gzopen, gzdopen, gzbuffer, gzsetparams, gzread,
   gzfread, gzwrite, gzfwrite, gzprintf, gzputs, gzputc, gzgets, gzgetc,
   gzungetc, gzflush, gzseek, gzrewind, gztell, gzoffset, gzeof, gzdirect,
   gzclose, gzclose_r, gzclose_w, gzerror, gzclearerr) is declared further
   below inside `#ifndef Z_SOLO ... #endif`, EXACTLY matching canonical zlib.h:
   the gz prototypes are visible by DEFAULT. A caller opts OUT only by defining
   Z_SOLO (zlib's compression-only configuration), e.g.:

       cc -DZ_SOLO your_app.c -lz

   Implementation note: cbindgen derives a POSITIVE `#if defined(WITH_GZFILEOP)`
   guard from the positive Cargo cfg `feature = "gz-io"` and cannot itself emit
   an `#ifndef` guard, so `build.rs` rewrites that guard to the canonical
   `#ifndef Z_SOLO` after generation. This gating affects ONLY the C
   declarations a direct consumer of this header sees; it does NOT affect:
     * the drop-in RELINK path -- programs built against the canonical system
       zlib.h get the gz API by default and link this Rust libz.so / libz.a
       unchanged (all 26 gz symbols are always exported);
     * symbol export -- every gz symbol is present in libz.so / libz.a;
     * signature / ABI parity -- the gz prototypes are identical to canonical
       zlib. */

/*
 Opaque counterpart of the C `struct internal_state;` forward declaration.

 The real deflate/inflate state is owned by the safe `zlib-rs` core and is
 never visible to C callers; the C ABI only ever holds it behind a pointer
 (`z_stream.state`). The zero-sized private field makes this type impossible
 to construct or copy by value and keeps it FFI-opaque, exactly mirroring the
 C contract.
 */
typedef struct internal_state {
    uint8_t _private[0];
} internal_state;

/*
 C `alloc_func`: `voidpf (*alloc_func)(voidpf opaque, uInt items, uInt size)`.

 Wrapped in [`Option`] because a null `zalloc` is the documented "use the
 default allocator" sentinel. The null-pointer optimization makes
 `Option<extern "C" fn ...>` exactly pointer-sized, so this stays
 ABI-compatible with a bare C function pointer.
 */
typedef void *(*alloc_func)(void *opaque, unsigned int items, unsigned int size);

/*
 C `free_func`: `void (*free_func)(voidpf opaque, voidpf address)`.

 `Option`-wrapped for the same nullability/ABI reason as [`alloc_func`].
 */
typedef void (*free_func)(void *opaque, void *address);

/*
 C `struct z_stream_s` — the public streaming state shared with applications.

 Layout matches `zlib.h` byte-for-byte. `next_in`/`next_out` are the I/O
 cursors, `avail_in`/`avail_out` the remaining byte counts, `total_in`/
 `total_out` running totals, `msg` the last error string, `state` the opaque
 internal state, `zalloc`/`zfree`/`opaque` the optional custom allocator
 hooks, `data_type` the data-type guess / inflate decode state, `adler` the
 running Adler-32 (zlib) or CRC-32 (gzip) checksum, and `reserved` unused.
 */
typedef struct z_stream_s {
    /*
     `z_const Bytef *next_in` — next input byte.
     */
    const uint8_t *next_in;
    /*
     `uInt avail_in` — number of bytes available at `next_in`.
     */
    unsigned int avail_in;
    /*
     `uLong total_in` — total number of input bytes read so far.
     */
    unsigned long total_in;
    /*
     `Bytef *next_out` — next output byte will go here.
     */
    uint8_t *next_out;
    /*
     `uInt avail_out` — remaining free space at `next_out`.
     */
    unsigned int avail_out;
    /*
     `uLong total_out` — total number of bytes output so far.
     */
    unsigned long total_out;
    /*
     `z_const char *msg` — last error message, NULL if no error.
     */
    const char *msg;
    /*
     `struct internal_state FAR *state` — not visible by applications.
     */
    struct internal_state *state;
    /*
     `alloc_func zalloc` — used to allocate the internal state.
     */
    alloc_func zalloc;
    /*
     `free_func zfree` — used to free the internal state.
     */
    free_func zfree;
    /*
     `voidpf opaque` — private data object passed to `zalloc`/`zfree`.
     */
    void *opaque;
    /*
     `int data_type` — best guess about the data type (deflate), or the
     decoding state (inflate).
     */
    int data_type;
    /*
     `uLong adler` — Adler-32 or CRC-32 value of the uncompressed data.
     */
    unsigned long adler;
    /*
     `uLong reserved` — reserved for future use.
     */
    unsigned long reserved;
} z_stream_s;

/*
 C `typedef struct z_stream_s ... z_stream;`.
 */
typedef struct z_stream_s z_stream;

/*
 C `typedef z_stream FAR *z_streamp;`.
 */
typedef z_stream *z_streamp;

/*
 C `struct gz_header_s` — gzip header information passed to and from zlib
 routines (see RFC 1952). Layout matches `zlib.h` byte-for-byte.
 */
typedef struct gz_header_s {
    /*
     `int text` — true if compressed data believed to be text.
     */
    int text;
    /*
     `uLong time` — modification time.
     */
    unsigned long time;
    /*
     `int xflags` — extra flags (not used when writing a gzip file).
     */
    int xflags;
    /*
     `int os` — operating system.
     */
    int os;
    /*
     `Bytef *extra` — pointer to extra field or NULL if none.
     */
    uint8_t *extra;
    /*
     `uInt extra_len` — extra field length (valid if `extra != NULL`).
     */
    unsigned int extra_len;
    /*
     `uInt extra_max` — space at `extra` (only when reading header).
     */
    unsigned int extra_max;
    /*
     `Bytef *name` — pointer to zero-terminated file name or NULL.
     */
    uint8_t *name;
    /*
     `uInt name_max` — space at `name` (only when reading header).
     */
    unsigned int name_max;
    /*
     `Bytef *comment` — pointer to zero-terminated comment or NULL.
     */
    uint8_t *comment;
    /*
     `uInt comm_max` — space at `comment` (only when reading header).
     */
    unsigned int comm_max;
    /*
     `int hcrc` — true if there was or will be a header CRC.
     */
    int hcrc;
    /*
     `int done` — true when done reading gzip header (not used when writing).
     */
    int done;
} gz_header_s;

/*
 C `typedef struct gz_header_s ... gz_header;`.
 */
typedef struct gz_header_s gz_header;

/*
 C `typedef gz_header FAR *gz_headerp;`.
 */
typedef gz_header *gz_headerp;

/*
 C `in_func` (used by `inflateBack`):
 `unsigned (*in_func)(void FAR *, z_const unsigned char FAR * FAR *)`.
 */
typedef unsigned int (*in_func)(void*, const uint8_t**);

/*
 C `out_func` (used by `inflateBack`):
 `int (*out_func)(void FAR *, unsigned char FAR *, unsigned)`.
 */
typedef int (*out_func)(void*, uint8_t*, unsigned int);

/*
 C `z_crc_t` (`Z_U4`): a 32-bit unsigned integer used for CRC-32 values.
 */
typedef uint32_t z_crc_t;

/*
 C `z_off64_t`: a 64-bit signed file offset (`off64_t` / `long long`).
 */
typedef int64_t z_off64_t;

/*
 C `struct gzFile_s` — the abbreviated, **prefix-compatible header** of the
 gzip file descriptor.

 `zlib.h` deliberately exposes only these first three fields so the C
 `gzgetc(g)` macro can inline its fast path
 `((g)->have ? ((g)->have--, (g)->pos++, *((g)->next)++) : (gzgetc)(g))`.

 **Contract for `translate.rs` / `lib.rs`:** the *real* gz state is much
 larger and is owned by the safe core's `GzState`. The shim must allocate a
 `Box`ed full-state value whose first three fields are layout-compatible with
 `gzFile_s` (`have`, `next`, `pos`, in this order), and only ever hand a
 `*mut gzFile_s` to C. That way the inlined C macro and the `gzgetc`
 fallback function agree on where `have`/`next`/`pos` live. C callers must
 never touch these fields except through the `gzgetc` macro.

 These type definitions are intentionally **ungated**: `cbindgen` emits them
 whenever `!Z_SOLO` so the generated header is complete. Only the gz
 *functions* in `lib.rs` are `#[cfg(feature = "gz-io")]`-gated, not these
 types.
 */
typedef struct gzFile_s {
    /*
     `unsigned have` — bytes available in the inline read-ahead buffer.
     */
    unsigned int have;
    /*
     `unsigned char *next` — cursor into the inline read-ahead buffer.
     */
    uint8_t *next;
    /*
     `z_off64_t pos` — current position in the uncompressed data.
     */
    z_off64_t pos;
} gzFile_s;

/*
 C `typedef struct gzFile_s *gzFile;` — the semi-opaque gzip file descriptor.
 */
typedef struct gzFile_s *gzFile;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 `deflateInit2_` — full compressor initialization (`zlib.h` L1907).

 Validates the version/`sizeof(z_stream)` guard and a non-null `strm`, maps
 the C `strategy` to the core [`Strategy`], allocates the owned state, and
 stashes it in `z_stream.state`. `windowBits` overloading (zlib/raw/gzip/auto)
 is handled by the core — the raw value is passed straight through.

 # Safety

 `strm` (if non-null) and `version` must satisfy the C `deflateInit2_`
 contract (a valid `z_stream` and a NUL-terminated version string).
 */
int deflateInit2_(z_streamp strm,
                  int level,
                  int method,
                  int windowBits,
                  int memLevel,
                  int strategy,
                  const char *version,
                  int stream_size);

/*
 `deflateInit_` — convenience initializer (`zlib.h` L1903): `deflateInit2_`
 with `method = Z_DEFLATED`, `windowBits = MAX_WBITS`,
 `memLevel = DEF_MEM_LEVEL`, `strategy = Z_DEFAULT_STRATEGY`.

 # Safety

 As [`deflateInit2_`].
 */
int deflateInit_(z_streamp strm, int level, const char *version, int stream_size);

/*
 `deflate` — compress/flush one step (`zlib.h` L744).

 # Safety

 `strm` must be null or a valid `z_streamp` whose `next_in`/`next_out` honor
 `avail_in`/`avail_out`.
 */
int deflate(z_streamp strm, int flush);

/*
 `deflateEnd` — free the compressor (`zlib.h` L759). Returns `Z_DATA_ERROR`
 if called mid-stream (pending output), `Z_STREAM_ERROR` for an invalid
 state, else `Z_OK`.

 # Safety

 `strm` must be null or a valid `z_streamp`.
 */
int deflateEnd(z_streamp strm);

/*
 `deflateReset` — reset for a fresh stream, keeping allocations (`zlib.h`
 L1010).

 # Safety

 `strm` must be null or a valid `z_streamp`.
 */
int deflateReset(z_streamp strm);

/*
 `deflateParams` — change level/strategy mid-stream (`zlib.h` L867), flushing
 pending output through `next_out` if required. Forms the input/output slices
 and writes the per-call results back exactly as `deflate` does.

 # Safety

 `strm` must be null or a valid `z_streamp` whose buffers honor `avail_*`.
 */
int deflateParams(z_streamp strm, int level, int strategy);

/*
 `deflateBound` — upper bound on the compressed size of `sourceLen` bytes
 (`zlib.h` L768). Uses the stream's exact bound when a deflate state is
 present, else the conservative one-shot bound.

 # Safety

 `strm` must be null or a valid `z_streamp`.
 */
unsigned long deflateBound(z_streamp strm, unsigned long sourceLen);

/*
 `deflatePrime` — insert bits into the output stream (`zlib.h` L1031).

 # Safety

 `strm` must be null or a valid `z_streamp`.
 */
int deflatePrime(z_streamp strm, int bits, int value);

/*
 `deflateSetDictionary` — preset the compressor dictionary (`zlib.h` L633).

 # Safety

 `strm` must be null or a valid `z_streamp`; `(dictionary, dictLength)` must
 be a valid buffer (or `dictionary` null with `dictLength == 0`).
 */
int deflateSetDictionary(z_streamp strm, const uint8_t *dictionary, unsigned int dictLength);

/*
 `deflateGetDictionary` — read back the sliding-window dictionary (`zlib.h`
 L658). Writes the dictionary length through `dictLength` and, when
 `dictionary` is non-null, copies that many bytes into it.

 # Safety

 `strm` must be null or a valid `z_streamp`. When non-null, `dictionary` must
 be writable for the returned dictionary length and `dictLength` writable.
 */
int deflateGetDictionary(z_streamp strm, uint8_t *dictionary, unsigned int *dictLength);

/*
 `deflateSetHeader` — supply a gzip header for a `windowBits` gzip stream
 (`zlib.h` L835). The core requires `wrap == 2` (gzip) and returns
 `Z_STREAM_ERROR` otherwise.

 # Safety

 `strm` must be null or a valid `z_streamp`; `head` (if non-null) a valid
 `gz_header` per [`gzheader_from_c`].
 */
int deflateSetHeader(z_streamp strm, gz_headerp head);

/*
 `deflateCopy` — duplicate a compressor stream (`zlib.h` L991).

 # Safety

 `dest` and `source` must be null or valid `z_streamp`s.
 */
int deflateCopy(z_streamp dest, z_streamp source);

/*
 `deflateTune` — fine-tune the internal match parameters (`zlib.h` L786).

 # Safety

 `strm` must be null or a valid `z_streamp`.
 */
int deflateTune(z_streamp strm, int good_length, int max_lazy, int nice_length, int max_chain);

/*
 `deflatePending` — report bytes/bits pending output (`zlib.h` L1019).

 # Safety

 `strm` must be null or a valid `z_streamp`; `pending`/`bits` null or valid
 writable pointers.
 */
int deflatePending(z_streamp strm, unsigned int *pending, int *bits);

/*
 C `inflateInit2_` — allocate and initialize an inflate stream with explicit
 `windowBits` (honoring zlib/raw/gzip/auto overloading, which the core
 decodes — the boundary passes the raw value through unchanged).
 */
int inflateInit2_(z_streamp strm, int windowBits, const char *version, int stream_size);

/*
 C `inflateInit_` — `inflateInit2_` with the default window size
 (`MAX_WBITS` = 15, i.e. a zlib-wrapped 32 KiB window).
 */
int inflateInit_(z_streamp strm, const char *version, int stream_size);

/*
 C `inflate` — run one decompression step, then (std) write back any
 requested gzip header fields into the caller's registered `gz_header`.
 */
int inflate(z_streamp strm, int flush);

/*
 C `inflateEnd` — free the inflate state (RAII drop of the owning box) and
 forget any gzip-header registration for this stream.
 */
int inflateEnd(z_streamp strm);

/*
 C `inflateReset` — reset the stream to a fresh post-init state, preserving
 the allocated window and `windowBits`. Zeros the C-visible counters and
 republishes the initial adler (`wrap & 1`).
 */
int inflateReset(z_streamp strm);

/*
 C `inflateReset2` — like `inflateReset` but also reselect the wrap/window
 from a new `windowBits` (zlib/raw/gzip/auto overloading decoded by the core).
 */
int inflateReset2(z_streamp strm, int windowBits);

/*
 C `inflateSync` — skip forward to the next possible full flush point to
 recover from corrupted input, advancing the C input cursor by what the
 byte-resync consumed.
 */
int inflateSync(z_streamp strm);

/*
 C `inflateCopy` — deep-copy an inflate stream (state + window) into a fresh
 destination stream.
 */
int inflateCopy(z_streamp dest, z_streamp source);

/*
 C `inflatePrime` — insert `bits` (0..=16) bits of `value` ahead of the input
 stream (used to resume mid-byte, e.g. after `inflateBack`).
 */
int inflatePrime(z_streamp strm, int bits, int value);

/*
 C `inflateMark` — return the bit/byte position packed as a `long` (high
 bits = bytes consumed of the current block, low 16 bits = bits remaining in
 the bit accumulator). Returns `-(1 << 16)` for an invalid state.

 NOTE: the return type is `c_long`, NOT `c_int` — this is a deliberate
 `zlib.h` quirk preserved for byte-for-byte ABI parity.
 */
long inflateMark(z_streamp strm);

/*
 C `inflateGetHeader` — request that the gzip header from a gzip-wrapped
 stream be captured and written into the caller's `gz_header` as `inflate`
 parses it.
 */
int inflateGetHeader(z_streamp strm, gz_headerp head);

/*
 C `inflateSetDictionary` — set the preset dictionary used to decompress a
 raw stream (or one reporting `Z_NEED_DICT`).
 */
int inflateSetDictionary(z_streamp strm, const uint8_t *dictionary, unsigned int dictLength);

/*
 C `inflateGetDictionary` — copy the sliding-window dictionary out to the
 caller. Queries the length first (null buffer), then copies when a non-null
 `dictionary` is supplied; writes the length back through `dictLength`.
 */
int inflateGetDictionary(z_streamp strm, uint8_t *dictionary, unsigned int *dictLength);

/*
 C `inflateBackInit_` — initialize a stream for the callback-driven
 `inflateBack` decoder. The caller's `window` pointer must be non-null (per
 the C contract) but is used only as internal scratch in C; our core owns its
 own `1 << windowBits` window, which is behaviorally equivalent.
 */
int inflateBackInit_(z_streamp strm,
                     int windowBits,
                     uint8_t *window,
                     const char *version,
                     int stream_size);

/*
 C `inflateBack` — decompress a raw DEFLATE stream using caller-supplied
 `in()` / `out()` callbacks instead of `next_in`/`next_out`. The single most
 pointer-heavy inflate symbol: it bridges the two C callbacks to the core's
 `FnMut() -> &[u8]` / `FnMut(&[u8]) -> bool` closures.
 */
int inflateBack(z_streamp strm, in_func in_, void *in_desc, out_func out, void *out_desc);

/*
 C `inflateBackEnd` — free an `inflateBack` stream. Equivalent to dropping the
 owning box (RAII); there is no status beyond `Z_OK` on a valid state.
 */
int inflateBackEnd(z_streamp strm);

/*
 C `compress2` — one-shot compress `source` into `dest` at the given `level`.
 `destLen` is in/out (capacity in, produced out).
 */
int compress2(uint8_t *dest,
              unsigned long *destLen,
              const uint8_t *source,
              unsigned long sourceLen,
              int level);

/*
 C `compress` — `compress2` at the default compression level.
 */
int compress(uint8_t *dest, unsigned long *destLen, const uint8_t *source, unsigned long sourceLen);

/*
 C `compressBound` — upper bound on the compressed size of `sourceLen` bytes.
 Delegates to the core's `compress_bound` (which reproduces the zlib formula).
 */
unsigned long compressBound(unsigned long sourceLen);

/*
 C `uncompress` — one-shot decompress `source` into `dest`. `destLen` is
 in/out (capacity in, produced out).
 */
int uncompress(uint8_t *dest,
               unsigned long *destLen,
               const uint8_t *source,
               unsigned long sourceLen);

/*
 C `uncompress2` — like `uncompress`, but `sourceLen` is in/out: on return it
 holds the number of source bytes actually consumed (the core reports the
 consumed count alongside the produced count).
 */
int uncompress2(uint8_t *dest,
                unsigned long *destLen,
                const uint8_t *source,
                unsigned long *sourceLen);

/*
 C `adler32` — update a running Adler-32 with `(buf, len)`. A NULL `buf`
 returns the initial value `1`.
 */
unsigned long adler32(unsigned long adler, const uint8_t *buf, unsigned int len);

/*
 C `adler32_z` — `adler32` with a `size_t` length (large-buffer variant).
 */
unsigned long adler32_z(unsigned long adler, const uint8_t *buf, size_t len);

/*
 C `adler32_combine` — combine two Adler-32 values as if the two blocks (the
 second of length `len2`) had been checksummed in sequence.
 */
unsigned long adler32_combine(unsigned long adler1, unsigned long adler2, off_t len2);

/*
 C `crc32` — update a running CRC-32 (IEEE) with `(buf, len)`. A NULL `buf`
 returns the initial value `0`.
 */
unsigned long crc32(unsigned long crc, const uint8_t *buf, unsigned int len);

/*
 C `crc32_z` — `crc32` with a `size_t` length (large-buffer variant).
 */
unsigned long crc32_z(unsigned long crc, const uint8_t *buf, size_t len);

/*
 C `crc32_combine` — combine two CRC-32 values as if the two blocks (the
 second of length `len2`) had been CRC'd in sequence.
 */
unsigned long crc32_combine(unsigned long crc1, unsigned long crc2, off_t len2);

/*
 C `crc32_combine_gen` — precompute the combine operator for a second block
 of length `len2`, for repeated use with `crc32_combine_op`.
 */
unsigned long crc32_combine_gen(off_t len2);

/*
 C `crc32_combine_op` — combine two CRC-32 values using a precomputed operator
 `op` (from `crc32_combine_gen`).
 */
unsigned long crc32_combine_op(unsigned long crc1, unsigned long crc2, unsigned long op);

/*
 C `get_crc_table` — return a pointer to the 256-entry CRC-32 lookup table
 (`z_crc_t` = `u32`), as some legacy consumers expect.
 */
const z_crc_t *get_crc_table(void);

/*
 C `zlibVersion` — return the runtime ABI version string. This MUST be
 exactly `"1.3.2.1-motley"` (the C `ZLIB_VERSION` define), independent of the
 crate's Cargo semver.
 */
const char *zlibVersion(void);

/*
 C `zlibCompileFlags` — return the bitfield describing the compile-time type
 sizes and options (computed by the core to match the running platform's
 `uInt`/`uLong`/`voidpf`/`z_off_t` widths).
 */
unsigned long zlibCompileFlags(void);

/*
 C `zError` — map a zlib error code to its `'static` NUL-terminated message
 string (backs the core's `err_msg` table).
 */
const char *zError(int err);

#ifndef Z_SOLO
/*
 C `gzopen` — open `path` for gzip reading/writing per `mode` (e.g. `"rb"`,
 `"wb9"`). Returns NULL on failure.
 */
gzFile gzopen(const char *path, const char *mode);
#endif

#ifndef Z_SOLO
/*
 C `gzdopen` — wrap an already-open OS file descriptor `fd` (ownership is
 transferred, as in C) for gzip I/O per `mode`. Returns NULL on failure.
 */
gzFile gzdopen(int fd, const char *mode);
#endif

#ifndef Z_SOLO
/*
 C `gzbuffer` — set the internal buffer size for `file` (before the first
 read/write). Returns 0 on success, -1 on error.
 */
int gzbuffer(gzFile file, unsigned int size);
#endif

#ifndef Z_SOLO
/*
 C `gzsetparams` — change the compression `level`/`strategy` mid-stream.
 */
int gzsetparams(gzFile file, int level, int strategy);
#endif

#ifndef Z_SOLO
/*
 C `gzread` — read up to `len` uncompressed bytes into `buf`. Returns the
 number of bytes read (0 at EOF) or -1 on error.
 */
int gzread(gzFile file, void *buf, unsigned int len);
#endif

#ifndef Z_SOLO
/*
 C `gzfread` — read `nitems` items of `size` bytes each into `buf`. Returns
 the number of full items read. Guards against `size * nitems` overflow
 (returns 0, as C does).
 */
size_t gzfread(void *buf, size_t size, size_t nitems, gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzwrite` — write `len` uncompressed bytes from `buf`. Returns the number
 of bytes written, or 0 on error.
 */
int gzwrite(gzFile file, const void *buf, unsigned int len);
#endif

#ifndef Z_SOLO
/*
 C `gzfwrite` — write `nitems` items of `size` bytes each from `buf`. Returns
 the number of full items written. Guards against `size * nitems` overflow.
 */
size_t gzfwrite(const void *buf, size_t size, size_t nitems, gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzputs` — write the NUL-terminated string `s` (without its NUL). Returns
 the number of bytes written, or -1 on error.
 */
int gzputs(gzFile file, const char *s);
#endif

#ifndef Z_SOLO
/*
 C `gzputc` — write one byte `c`. Returns the byte written, or -1 on error.
 */
int gzputc(gzFile file, int c);
#endif

#ifndef Z_SOLO
/*
 C `gzgets` — read a line (up to `len - 1` bytes, plus a NUL) into `buf`.
 Returns `buf` on success, or NULL at EOF/on error.
 */
char *gzgets(gzFile file, char *buf, int len);
#endif

#ifndef Z_SOLO
/*
 C `gzgetc` — read one byte. Returns the byte (0..=255) or -1 at EOF/error.
 This is the function the generated `gzgetc` macro falls back to (we keep the
 inline `have` counter at 0 so the macro always calls here).
 */
int gzgetc(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzungetc` — push byte `c` back so the next read returns it. Returns `c`,
 or -1 on error.
 */
int gzungetc(int c, gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzflush` — flush pending output with the given `flush` mode.
 */
int gzflush(gzFile file, int flush);
#endif

#ifndef Z_SOLO
/*
 C `gzseek` — reposition `file` to `offset` per `whence` (`SEEK_SET`/
 `SEEK_CUR`). Returns the resulting uncompressed offset, or -1 on error.
 */
off_t gzseek(gzFile file, off_t offset, int whence);
#endif

#ifndef Z_SOLO
/*
 C `gzrewind` — reset `file` to the beginning (read mode only).
 */
int gzrewind(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gztell` — return the current uncompressed offset, or -1 on error.
 */
off_t gztell(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzoffset` — return the current compressed-file offset, or -1 on error.
 */
off_t gzoffset(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzeof` — return non-zero once the read end-of-file has been reached.
 */
int gzeof(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzdirect` — return non-zero if `file` is being read transparently (i.e.
 the input is not actually gzip-compressed).
 */
int gzdirect(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzclose` — flush (write mode), close, and free `file`. Consumes the
 handle (reconstructs the owning box and drops it = RAII close).
 */
int gzclose(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzclose_r` — the read-mode specialization of `gzclose`.
 */
int gzclose_r(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzclose_w` — the write-mode specialization of `gzclose` (flushes output).
 */
int gzclose_w(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzerror` — return the last error message for `file` and (if `errnum` is
 non-null) write the numeric code through it. The returned pointer stays
 valid until the next gz call on `file` (it is owned by the shim's `err_buf`).
 */
const char *gzerror(gzFile file, int *errnum);
#endif

#ifndef Z_SOLO
/*
 C `gzclearerr` — clear the error and end-of-file flags for `file`. (void.)
 */
void gzclearerr(gzFile file);
#endif

#ifndef Z_SOLO
/*
 C `gzprintf` — `printf`-style formatted write to a gz file.

 Renders `format` + the variadic arguments into the gz stream's CURRENT
 state-sized scratch buffer (honoring any caller `gzbuffer()` resize) and
 writes the result, routing through the shared
 [`zlib_rs::gz::gz_printf_into`] so the exact C vprintf-style overflow and
 accounting discipline is reused rather than re-implemented. Per C zlib,
 output that is empty, `size`-or-larger, or whose trailing NUL sentinel was
 overwritten is REJECTED: nothing is written and `0` is returned (it is never
 silently truncated). Returns the number of *uncompressed* bytes written, or
 a negative zlib error code.

 Available only under the nightly-only `c-variadic` feature (see the module
 note above); the `libz-rs-sys-cdylib` drop-in enables it by default.
 */
int gzprintf(gzFile file, const char *format, ...);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ZLIB_RS_H */
