//! CRC-32 (IEEE, reflected `0xEDB88320`), ported from zlib `crc32.c`;
//! bit-for-bit identical to C zlib.
//!
//! CRC-32 is the integrity check used by the gzip wrapper (RFC 1952): the
//! four-byte little-endian CRC-32 of the uncompressed data is written into the
//! gzip trailer, and the running value is tracked in `strm.adler` while a gzip
//! stream is being produced or consumed. Because the checksum is part of the
//! on-the-wire format, any deviation from the canonical algorithm would break
//! stream compatibility; this module therefore reproduces the C reference
//! exactly, including the `crc32_z`, `crc32_combine*`, `crc32_combine_gen*`,
//! `crc32_combine_op`, and `get_crc_table` variants.
//!
//! # Algorithm
//!
//! Two interchangeable engines produce the identical IEEE CRC-32:
//!
//! * **Scalar slice-by-8** (`crc32_scalar`) — the portable fallback. It folds
//!   eight input bytes per iteration through the eight-row lookup table that
//!   `build.rs` regenerates at build time (mirroring the 9,446-line upstream
//!   `crc32.h`, which is therefore never hand-ported). The byte loads use
//!   [`u32::from_le_bytes`], so the result is identical on little- and
//!   big-endian targets (AAP §0.6.4).
//! * **SIMD** (`crc32_simd`) — used when the `simd` feature is on. It delegates
//!   to the [`crc32fast`] crate, which selects a hardware-accelerated
//!   carry-less-multiply implementation at run time and computes the very same
//!   IEEE CRC-32. The `simd` feature is the default and targets ≥3× the scalar
//!   throughput (AAP §0.7.3).
//!
//! The GF(2) "combine" machinery ([`crc32_combine`] and friends) splices the
//! CRC of two concatenated buffers without rescanning the data, using the table
//! of `x^(2^n) mod p(x)` powers built at compile time.
//!
//! # Purity and portability
//!
//! This module is **`no_std`-clean**: the scalar paths use `core` only — no
//! `std`, no `alloc`, and **no `unsafe`**. (The only `unsafe` involved in a SIMD
//! build lives *inside* the `crc32fast` crate, never here.) It compiles
//! unchanged under the crate's `no-std` feature.
//!
//! # Examples
//!
//! ```
//! use zlib_rs::checksum::crc32::crc32;
//!
//! // Seed with 0 to begin a fresh checksum; this is the canonical IEEE check
//! // value for the string "123456789".
//! let c = crc32(0, b"123456789");
//! assert_eq!(c, 0xCBF4_3926);
//! ```

// The slice-by-8 CRC-32 tables are regenerated by the crate's `build.rs` (it
// mirrors the upstream `crc32.h` generator) and written to
// `${OUT_DIR}/crc32_table.rs`, which declares
// `pub(crate) static CRC_TABLE: [[u32; 256]; 8]` (and an unused flat alias
// `CRC_TABLE_0`). The generated module is wrapped here so the `#[allow(dead_code)]`
// scopes precisely to those generated items — silencing the warning for the
// `CRC_TABLE_0` alias this module does not consume, without masking dead code in
// the hand-written implementation. The `include!` path expression is verbatim
// per the build-script contract (AAP §0.3.1).
#[allow(dead_code)]
mod crc_table {
    include!(concat!(env!("OUT_DIR"), "/crc32_table.rs"));
}
use crc_table::CRC_TABLE;

/// Reflected IEEE CRC-32 polynomial (matches the `build.rs` table generator and
/// `#define POLY 0xedb88320` in `crc32.c`).
///
/// "Reflected" means the input bits are processed least-significant-bit first,
/// the convention used by zlib, gzip, PNG, and Ethernet. Private implementation
/// detail — intentionally **not** a public `Z_*` constant.
const POLY: u32 = 0xedb8_8320;

// ===========================================================================
// Scalar slice-by-8 core
// ===========================================================================

/// Update a running CRC-32 over `buf` using the portable slice-by-8 table.
///
/// `crc` is the previous CRC value (use `0` to start a fresh computation) and
/// the return is the updated CRC. This is bit-for-bit identical to canonical C
/// zlib — validated against the reference for lengths `0..11111`, for arbitrary
/// continuation split points, and for the combine paths.
///
/// The routine maintains the running value in its complemented form (`c =
/// !crc`) so the per-byte recurrence matches the C reference, complementing once
/// more on return. The bulk loop consumes eight bytes at a time: the first
/// little-endian word is mixed with the running CRC and folded through table
/// rows 7..4, and the second word through rows 3..0; the `chunks_exact`
/// remainder (0..7 trailing bytes) is finished with the classic byte-wise
/// recurrence against row 0. Using [`u32::from_le_bytes`] with explicit byte
/// arrays keeps the computation panic-free and endianness-independent.
///
/// Compiled whenever the `simd` feature is *off*, and additionally under `test`
/// so the SIMD/scalar parity test can compare the two engines directly.
#[cfg(any(not(feature = "simd"), test))]
fn crc32_scalar(crc: u32, buf: &[u8]) -> u32 {
    let mut c = !crc;
    let mut chunks = buf.chunks_exact(8);
    for chunk in &mut chunks {
        // Little-endian word loads make the result host-endianness-independent.
        let one = c ^ u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        let two = u32::from_le_bytes([chunk[4], chunk[5], chunk[6], chunk[7]]);
        c = CRC_TABLE[7][(one & 0xff) as usize]
            ^ CRC_TABLE[6][((one >> 8) & 0xff) as usize]
            ^ CRC_TABLE[5][((one >> 16) & 0xff) as usize]
            ^ CRC_TABLE[4][((one >> 24) & 0xff) as usize]
            ^ CRC_TABLE[3][(two & 0xff) as usize]
            ^ CRC_TABLE[2][((two >> 8) & 0xff) as usize]
            ^ CRC_TABLE[1][((two >> 16) & 0xff) as usize]
            ^ CRC_TABLE[0][((two >> 24) & 0xff) as usize];
    }
    for &b in chunks.remainder() {
        c = (c >> 8) ^ CRC_TABLE[0][((c ^ u32::from(b)) & 0xff) as usize];
    }
    !c
}

// ===========================================================================
// Optional SIMD path (crc32fast, gated by the `simd` feature)
// ===========================================================================

/// Update a running CRC-32 over `buf` using the SIMD-accelerated `crc32fast`
/// backend.
///
/// `crc32fast` computes the identical IEEE CRC-32 as zlib; seeding the hasher
/// with [`crc32fast::Hasher::new_with_initial`] continues from a previously
/// computed value, exactly matching C `crc32(crc, buf)`. The crate selects a
/// hardware carry-less-multiply path (e.g. SSE4.2/PCLMULQDQ or the AArch64 CRC
/// instructions) when available and falls back to a fast table method
/// otherwise — all `unsafe` is encapsulated inside `crc32fast`, never here.
///
/// Only compiled under the `simd` feature.
#[cfg(feature = "simd")]
#[inline]
fn crc32_simd(crc: u32, buf: &[u8]) -> u32 {
    let mut hasher = crc32fast::Hasher::new_with_initial(crc);
    hasher.update(buf);
    hasher.finalize()
}

// ===========================================================================
// Public single-buffer entry points
// ===========================================================================

/// Update a running CRC-32 checksum with the bytes of `buf`.
///
/// This is the core public routine (the C `crc32_z`, whose length argument is a
/// `z_size_t`). `crc` is the previous checksum value — use `0` to start a fresh
/// computation — and the returned value is the updated checksum. The result is
/// bit-for-bit identical to C zlib regardless of how the input is chunked, so
/// streaming the data in pieces yields the same value as a single call.
///
/// Dispatch is resolved at compile time by the `simd` feature: with `simd` on
/// (the default) it uses the accelerated [`crc32fast`] backend, otherwise the
/// portable slice-by-8 `crc32_scalar`. An empty `buf` returns `crc` unchanged,
/// so `crc32_z(0, b"") == 0`. (C returns `0` for a `Z_NULL` buffer; that
/// pointer-specific fast path is handled at the FFI boundary in `ffi.rs`.)
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::crc32_z;
///
/// // Feeding the data in two pieces yields the same result as one shot.
/// let one_shot = crc32_z(0, b"abcdefgh");
/// let piece = crc32_z(0, b"abcd");
/// let split = crc32_z(piece, b"efgh");
/// assert_eq!(one_shot, split);
/// ```
pub fn crc32_z(crc: u32, buf: &[u8]) -> u32 {
    // Exactly one of these `return`s is compiled, so there is no unreachable
    // code and the dispatch is a zero-cost compile-time choice.
    #[cfg(feature = "simd")]
    return crc32_simd(crc, buf);
    #[cfg(not(feature = "simd"))]
    return crc32_scalar(crc, buf);
}

/// Update a running CRC-32 checksum with the bytes of `buf`.
///
/// Equivalent to [`crc32_z`]; provided to mirror the C public API where
/// `crc32` (with a 32-bit length) delegates to `crc32_z` (with a `size_t`
/// length). Seed `crc` with `0` to start a fresh checksum.
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::crc32;
///
/// assert_eq!(crc32(0, b""), 0);
/// assert_eq!(crc32(0, b"123456789"), 0xCBF4_3926);
/// ```
#[inline]
pub fn crc32(crc: u32, buf: &[u8]) -> u32 {
    crc32_z(crc, buf)
}

// ===========================================================================
// GF(2) polynomial arithmetic for combining CRCs
// ===========================================================================
//
// A CRC-32 is the remainder of the message polynomial divided by the CRC
// polynomial p(x), all computed in GF(2) (coefficients mod 2). To splice the
// CRC of `b` onto the CRC of `a` (forming the CRC of `a ++ b`) without
// rescanning `a`, the CRC of `a` must be advanced by `len(b)` zero bytes, which
// is a multiplication by `x^(8*len(b)) mod p(x)`. The helpers below implement
// that polynomial multiplication and the table of repeated-squaring powers that
// makes the advance run in O(log len) multiplies.

/// Multiply two polynomials modulo `p(x)` (the reflected CRC polynomial).
///
/// Operates on the reflected (LSB-first) bit representation used throughout
/// zlib. For speed — and to match the C reference exactly — this requires that
/// `a` not be zero; the loop terminates as soon as the highest remaining set bit
/// of `a` has been consumed. A zero `a` would loop forever, so every caller
/// guards against it (see [`crc32_combine_op`], which returns early when its
/// `op` is zero).
///
/// Declared `const fn` so it can build the compile-time [`X2N_TABLE`].
const fn multmodp(a: u32, b: u32) -> u32 {
    let mut m: u32 = 1u32 << 31;
    let mut p: u32 = 0;
    let mut b = b;
    loop {
        if a & m != 0 {
            p ^= b;
            if a & (m - 1) == 0 {
                return p;
            }
        }
        m >>= 1;
        b = if b & 1 != 0 { (b >> 1) ^ POLY } else { b >> 1 };
    }
}

/// Build the table of `x^(2^n) mod p(x)` for `n = 0..32`.
///
/// `X2N_TABLE[0]` is `x^1` (the reflected representation `1 << 30`), and each
/// subsequent entry squares the previous one via [`multmodp`], so
/// `X2N_TABLE[n] == x^(2^n) mod p(x)`. Mirrors the `x2n_table` initialization in
/// `crc32.c::make_crc_table()`. Evaluated at compile time.
const fn build_x2n_table() -> [u32; 32] {
    let mut t = [0u32; 32];
    t[0] = 1u32 << 30; // x^1
    let mut n = 1;
    while n < 32 {
        t[n] = multmodp(t[n - 1], t[n - 1]);
        n += 1;
    }
    t
}

/// `X2N_TABLE[n] = x^(2^n) mod p(x)`; the powers used to advance a CRC over a
/// run of zero bytes when combining. Built once at compile time.
const X2N_TABLE: [u32; 32] = build_x2n_table();

/// Return `x^(8*n) mod p(x)`, i.e. the polynomial that advances a CRC over `n`
/// zero bytes, where the byte count `n` is consumed starting at table index `k`.
///
/// Walks the bits of `n`, folding in `X2N_TABLE[k & 31]` (the next power of two)
/// for each set bit, exactly as `crc32.c::x2nmodp()` does. Seeds the accumulator
/// with `x^0 == 1` (the reflected representation `1 << 31`). Callers pass `k = 3`
/// to convert a *byte* length into the bit-length exponent (`8 = 2^3`).
fn x2nmodp(mut n: u64, mut k: u32) -> u32 {
    let mut p: u32 = 1u32 << 31; // x^0 == 1
    while n != 0 {
        if n & 1 != 0 {
            p = multmodp(X2N_TABLE[(k & 31) as usize], p);
        }
        n >>= 1;
        k += 1;
    }
    p
}

// ===========================================================================
// Public combine entry points
// ===========================================================================

/// Generate the combine operator for a second buffer of length `len2` (64-bit
/// length variant).
///
/// The returned "operator" is `x^(8*len2) mod p(x)`; pass it to
/// [`crc32_combine_op`] together with the two CRCs to splice them. Generating
/// the operator once and reusing it across many identically sized combines (the
/// purpose this split serves in the C API) avoids recomputing the power each
/// time. A negative `len2` is invalid and returns `0`, matching C zlib.
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::{crc32, crc32_combine_gen64, crc32_combine_op};
///
/// let a = b"Hello, ";
/// let b = b"world!";
/// let op = crc32_combine_gen64(b.len() as i64);
/// let combined = crc32_combine_op(crc32(0, a), crc32(0, b), op);
/// assert_eq!(combined, crc32(0, b"Hello, world!"));
/// ```
pub fn crc32_combine_gen64(len2: i64) -> u32 {
    if len2 < 0 { 0 } else { x2nmodp(len2 as u64, 3) }
}

/// Generate the combine operator for a second buffer of length `len2` (32-bit
/// length variant).
///
/// Identical in behavior to [`crc32_combine_gen64`]; both share one
/// implementation because Rust's `i64` length already covers the range the C
/// API splits across `z_off_t` and `z_off64_t`.
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::{crc32_combine_gen, crc32_combine_gen64};
///
/// assert_eq!(crc32_combine_gen(42), crc32_combine_gen64(42));
/// ```
#[inline]
pub fn crc32_combine_gen(len2: i64) -> u32 {
    crc32_combine_gen64(len2)
}

/// Combine two CRC-32 checksums using a precomputed operator from
/// [`crc32_combine_gen`] / [`crc32_combine_gen64`].
///
/// Computes `multmodp(op, crc1) ^ crc2`, which is the CRC of the first buffer
/// (advanced over the length of the second by `op`) spliced with the CRC of the
/// second buffer. Returns `crc2` blended over an advanced `crc1`, i.e. the CRC
/// of the two buffers concatenated.
///
/// A zero `op` returns `0`. Operators produced by the `*_combine_gen*` functions
/// for a valid (non-negative) length are always nonzero — `x^(8*len2) mod p(x)`
/// can never be the zero polynomial because `x` and `p(x)` are coprime (the CRC
/// polynomial has a nonzero constant term) — so this guard is a no-op for correct
/// inputs. It exists only to keep `multmodp` (which requires a nonzero first
/// argument) from looping forever if misused; the C reference is undefined/hangs
/// for `op == 0`.
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::{crc32, crc32_combine_gen, crc32_combine_op};
///
/// let a = b"foo";
/// let b = b"bar";
/// let op = crc32_combine_gen(b.len() as i64);
/// assert_eq!(
///     crc32_combine_op(crc32(0, a), crc32(0, b), op),
///     crc32(0, b"foobar")
/// );
/// ```
pub fn crc32_combine_op(crc1: u32, crc2: u32, op: u32) -> u32 {
    if op == 0 {
        return 0;
    }
    multmodp(op, crc1) ^ crc2
}

/// Combine two CRC-32 checksums into one, as if the second buffer had been
/// appended to the first (64-bit length variant).
///
/// Given `crc1 = crc32(0, a)` and `crc2 = crc32(0, b)` where `b` has length
/// `len2`, this returns `crc32(0, [a, b].concat())` without rescanning the data.
/// A negative `len2` produces the value for `op == 0` (`0`). Equivalent to
/// generating the operator with [`crc32_combine_gen64`] and applying it with
/// [`crc32_combine_op`].
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::{crc32, crc32_combine64};
///
/// let left = crc32(0, b"foo");
/// let right = crc32(0, b"bar");
/// assert_eq!(crc32_combine64(left, right, 3), crc32(0, b"foobar"));
/// ```
pub fn crc32_combine64(crc1: u32, crc2: u32, len2: i64) -> u32 {
    crc32_combine_op(crc1, crc2, crc32_combine_gen64(len2))
}

/// Combine two CRC-32 checksums into one (32-bit length variant).
///
/// Identical in behavior to [`crc32_combine64`]; both delegate to the same
/// machinery because Rust's `i64` length spans the 64-bit range the C API splits
/// across `z_off_t` and `z_off64_t`. `crc1` is the checksum of the first buffer,
/// `crc2` the checksum of the second, and `len2` the length (in bytes) of the
/// second buffer.
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::{crc32, crc32_combine};
///
/// let left = crc32(0, b"Hello, ");
/// let right = crc32(0, b"world!");
/// let whole = crc32(0, b"Hello, world!");
/// assert_eq!(crc32_combine(left, right, b"world!".len() as i64), whole);
/// ```
#[inline]
pub fn crc32_combine(crc1: u32, crc2: u32, len2: i64) -> u32 {
    crc32_combine64(crc1, crc2, len2)
}

// ===========================================================================
// CRC table accessor
// ===========================================================================

/// Return the standard 256-entry single-byte CRC-32 table (matches C
/// `get_crc_table()`).
///
/// This is row 0 of the slice-by-8 table — the canonical `crc_table` from the
/// upstream `crc32.h`, with `get_crc_table()[n]` equal to the CRC-32 of the
/// single byte `n` (in the reflected representation). Some callers use it to
/// drive their own byte-wise CRC loops. It references `CRC_TABLE` directly so
/// the table stays live under every feature combination — including a `simd`
/// build where `crc32_scalar` is compiled out.
///
/// # Examples
///
/// ```
/// use zlib_rs::checksum::crc32::get_crc_table;
///
/// let table = get_crc_table();
/// assert_eq!(table[0], 0x0000_0000);
/// assert_eq!(table[1], 0x7707_3096);
/// ```
pub fn get_crc_table() -> &'static [u32; 256] {
    &CRC_TABLE[0]
}

#[cfg(test)]
mod tests {
    use super::{
        crc32, crc32_combine, crc32_combine_gen, crc32_combine_gen64, crc32_combine_op,
        crc32_combine64, crc32_z, get_crc_table,
    };

    /// Deterministic pseudo-random buffer generator. Mirrors the Python oracle
    /// generator `bytes((i*131 + 17) & 0xff for i in range(n))`, so the pinned
    /// CRC values below are exactly what canonical C zlib produces for these
    /// inputs.
    fn gen_buf(n: usize) -> Vec<u8> {
        (0..n).map(|i| ((i * 131 + 17) & 0xff) as u8).collect()
    }

    #[test]
    fn known_answer_vectors() {
        // Pinned against canonical C zlib (verified via Python's `zlib`).
        assert_eq!(crc32(0, b""), 0x0000_0000);
        assert_eq!(crc32(0, b"a"), 0xE8B7_BE43);
        assert_eq!(crc32(0, b"abc"), 0x3524_41C2);
        // The universally published IEEE CRC-32 check value.
        assert_eq!(crc32(0, b"123456789"), 0xCBF4_3926);
        assert_eq!(
            crc32(0, b"The quick brown fox jumps over the lazy dog"),
            0x414F_A339
        );
    }

    #[test]
    fn empty_buffer_is_identity() {
        // A fresh (seed 0) checksum of no data is 0, and an empty buffer never
        // changes the running value.
        assert_eq!(crc32(0, b""), 0);
        assert_eq!(crc32_z(0, b""), 0);
        let seed = 0x1234_5678;
        assert_eq!(crc32(seed, b""), seed);
        assert_eq!(crc32_z(seed, b""), seed);
    }

    #[test]
    fn crc_table_head_matches_header() {
        // Row 0 of the slice-by-8 table is the canonical `crc_table` from
        // `crc32.h`; its first four entries are the published constants.
        let table = get_crc_table();
        assert_eq!(table[0], 0x0000_0000);
        assert_eq!(table[1], 0x7707_3096);
        assert_eq!(table[2], 0xEE0E_612C);
        assert_eq!(table[3], 0x9909_51BA);
    }

    #[test]
    fn bulk_path_pinned_values() {
        // Buffers exercising the slice-by-8 bulk loop and its 0..7-byte
        // remainder, plus a large multi-iteration buffer, pinned against
        // canonical C zlib.
        assert_eq!(crc32(0, &gen_buf(16)), 0xBF22_721D);
        assert_eq!(crc32(0, &gen_buf(11105)), 0x2C88_FA4E);
        assert_eq!(crc32(0, &gen_buf(50000)), 0x5FD6_48B8);
    }

    #[test]
    fn crc32_matches_crc32_z() {
        // The two public single-buffer entry points must agree across the
        // boundary-relevant lengths (sub-word, exact words, word + remainder).
        for &len in &[0usize, 1, 7, 8, 9, 15, 16, 17, 64, 1000] {
            let data = gen_buf(len);
            assert_eq!(crc32(0, &data), crc32_z(0, &data), "len = {len}");
        }
    }

    #[test]
    fn continuation_equals_one_shot() {
        // Splitting the input anywhere must not change the checksum: this proves
        // the bulk/remainder boundary handling is chunking-independent.
        let data = gen_buf(40_000);
        let one_shot = crc32(0, &data);
        for &k in &[0usize, 1, 7, 8, 9, 15, 16, 17, 1000, 12_345, 40_000] {
            let split = crc32(crc32(0, &data[..k]), &data[k..]);
            assert_eq!(split, one_shot, "split at k = {k}");
        }
    }

    #[test]
    fn combine_equals_concatenation() {
        // crc32_combine of the two parts equals the checksum of the whole.
        let cases: [(Vec<u8>, Vec<u8>); 6] = [
            (Vec::new(), Vec::new()),
            (b"a".to_vec(), b"b".to_vec()),
            (b"Hello, ".to_vec(), b"world!".to_vec()),
            (gen_buf(1_000), gen_buf(2_000)),
            (b"123456789".to_vec(), gen_buf(5_000)),
            (b"foo".to_vec(), Vec::new()), // empty second buffer -> len2 == 0
        ];
        for (first, second) in &cases {
            let crc_first = crc32(0, first);
            let crc_second = crc32(0, second);
            let mut whole = first.clone();
            whole.extend_from_slice(second);
            let expected = crc32(0, &whole);
            let len2 = second.len() as i64;
            assert_eq!(
                crc32_combine(crc_first, crc_second, len2),
                expected,
                "combine len2 = {len2}"
            );
            // The 64-bit variant must behave identically.
            assert_eq!(
                crc32_combine64(crc_first, crc_second, len2),
                expected,
                "combine64 len2 = {len2}"
            );
        }
    }

    #[test]
    fn combine_gen_op_compose_to_combine64() {
        // Generating the operator and applying it must equal the all-in-one
        // combine, and the 32-bit gen must equal the 64-bit gen.
        for (first, second) in &[
            (gen_buf(123), gen_buf(456)),
            (gen_buf(8), gen_buf(8)),
            (b"abc".to_vec(), b"defghij".to_vec()),
        ] {
            let crc_first = crc32(0, first);
            let crc_second = crc32(0, second);
            let len2 = second.len() as i64;

            let op64 = crc32_combine_gen64(len2);
            let op32 = crc32_combine_gen(len2);
            assert_eq!(op32, op64, "gen32 vs gen64 for len2 = {len2}");

            let composed = crc32_combine_op(crc_first, crc_second, op64);
            assert_eq!(
                composed,
                crc32_combine64(crc_first, crc_second, len2),
                "compose for len2 = {len2}"
            );
            // Valid operators (len2 >= 0) are never zero: x^(8*len2) mod p(x)
            // can never be the zero polynomial. (The bit-31 / x^0 coefficient,
            // however, is not always set — e.g. len2 == 1 gives 0x0080_0000.)
            assert_ne!(op64, 0, "operator must be nonzero for len2 = {len2}");
        }
    }

    #[test]
    fn combine_negative_length_uses_zero_op_path() {
        // A negative length makes combine_gen return 0, so combine_op takes its
        // op == 0 guard: the result is deterministic and the call does not hang.
        assert_eq!(crc32_combine_gen64(-1), 0);
        assert_eq!(crc32_combine_gen(-1), 0);
        assert_eq!(crc32_combine_op(0x1234_5678, 0x9ABC_DEF0, 0), 0);
        assert_eq!(crc32_combine64(0x1234_5678, 0x9ABC_DEF0, -1), 0);
        assert_eq!(crc32_combine(0x1234_5678, 0x9ABC_DEF0, -42), 0);
    }

    /// SIMD/scalar parity: when both engines are compiled (under the `simd`
    /// feature), the accelerated path must be bit-identical to the portable
    /// slice-by-8 table path for every buffer.
    #[cfg(feature = "simd")]
    #[test]
    fn simd_matches_scalar() {
        use super::{crc32_scalar, crc32_simd};
        for &len in &[0usize, 1, 7, 8, 9, 15, 16, 17, 64, 255, 1000, 4096, 11105] {
            let data = gen_buf(len);
            assert_eq!(
                crc32_simd(0, &data),
                crc32_scalar(0, &data),
                "simd vs scalar disagree at len = {len}"
            );
            // Non-zero seed (continuation) must also match.
            assert_eq!(
                crc32_simd(0xDEAD_BEEF, &data),
                crc32_scalar(0xDEAD_BEEF, &data),
                "simd vs scalar disagree (seeded) at len = {len}"
            );
        }
    }
}
