//! Checksum engine for `zlib-rs`: Adler-32 (RFC 1950) and CRC-32 (IEEE).
//!
//! Ported from zlib's `adler32.c` and `crc32.c`; both produce values that are
//! **bit-for-bit identical** to C zlib, including the `*_combine` variants that
//! back the zlib/gzip stream trailers and `strm.adler`.
//!
//! * [`adler32`](fn@adler32) / [`adler32_z`] — Adler-32 (modulo 65521).
//! * [`crc32`](fn@crc32) / [`crc32_z`] — CRC-32 (reflected polynomial
//!   `0xEDB88320`), slice-by-8 scalar table (generated by `build.rs`) with
//!   optional `crc32fast` SIMD acceleration under the `simd` feature.
//!
//! All scalar paths are `no_std`-clean (`core` only).
//!
//! # Module layout
//!
//! This file is the **module root** for the checksum engine. It carries no
//! algorithm logic of its own; it declares the two implementation submodules
//! and re-exports their public surface so the whole checksum API resolves under
//! a single path, `crate::checksum::<name>`:
//!
//! | Submodule          | C source    | Responsibility                                       |
//! |--------------------|-------------|------------------------------------------------------|
//! | [`mod@adler32`]    | `adler32.c` | Adler-32 running sum and length-combine helpers      |
//! | [`mod@crc32`]      | `crc32.c`   | IEEE CRC-32, slice-by-8 scalar table + optional SIMD |
//!
//! Both the `adler32` *module* and the `adler32` *function* are reachable from
//! this root simultaneously: a module and a value of the same name live in
//! different namespaces in Rust, so `checksum::adler32` (the module) and
//! `checksum::adler32` (the re-exported function) coexist without conflict. The
//! same holds for `crc32`. This mirrors zlib's flat C namespace, where the
//! header exposes the functions directly while the implementation is split
//! across translation units.
//!
//! # Public API ↔ C zlib
//!
//! Every symbol re-exported here mirrors a function declared in `zlib.h`, with
//! the identical name and equivalent semantics, so that both the idiomatic Rust
//! surface (`crate::checksum`) and the C-ABI shim (`crate::ffi`) can build on a
//! single, complete checksum namespace.
//!
//! ## Adler-32 — `adler32.c` → [`mod@adler32`]
//!
//! * [`adler32`](fn@adler32) — rolling Adler-32 over a byte slice, seeded with
//!   a prior value (use `1` to start fresh); the zlib `adler32` entry point.
//! * [`adler32_z`] — the slice-length form of [`adler32`](fn@adler32) (zlib
//!   `adler32_z`), which in C takes an explicit `z_size_t` length.
//! * [`adler32_combine`] — combine two Adler-32 values as though their inputs
//!   had been concatenated (zlib `adler32_combine`).
//! * [`adler32_combine64`] — the 64-bit-length companion to
//!   [`adler32_combine`] (zlib `adler32_combine64`).
//!
//! ## CRC-32 — `crc32.c` → [`mod@crc32`]
//!
//! * [`crc32`](fn@crc32) — rolling IEEE CRC-32 over a byte slice, seeded with a
//!   prior value (use `0` to start fresh); the zlib `crc32` entry point.
//! * [`crc32_z`] — the slice-length form of [`crc32`](fn@crc32) (zlib
//!   `crc32_z`).
//! * [`crc32_combine`] / [`crc32_combine64`] — combine two CRC-32 values for
//!   concatenated inputs (zlib `crc32_combine` / `crc32_combine64`).
//! * [`crc32_combine_gen`] / [`crc32_combine_gen64`] — precompute the combine
//!   operator for a fixed second-input length so repeated combines of equal
//!   length are cheap (zlib `crc32_combine_gen` / `crc32_combine_gen64`).
//! * [`crc32_combine_op`] — apply an operator produced by
//!   [`crc32_combine_gen`] to two CRC-32 values (zlib `crc32_combine_op`).
//! * [`get_crc_table`] — borrow the canonical 256-entry single-byte CRC-32
//!   lookup table (zlib `get_crc_table`).
//!
//! # Features and `no_std`
//!
//! This module root is **feature-agnostic**: it contains no `cfg`-gated code
//! and compiles unchanged under every feature combination (`default`, `std`,
//! `no-std`, and `simd`). All feature behavior lives in the submodules — most
//! notably the `simd` feature, which routes [`crc32`](fn@crc32) /
//! [`crc32_z`] through the `crc32fast` crate while every other code path
//! remains pure `core`. No `unsafe`, no `std`, and no `alloc` are used at this
//! level, so the re-export surface is available identically in hosted and
//! `no_std` builds.

pub mod adler32;
pub mod crc32;

// Re-export the complete Adler-32 surface from `adler32.c`. `#[doc(inline)]`
// folds each function's documentation directly into this module's rendered
// docs (rather than linking out to the submodule), reproducing zlib.h's single
// flat API namespace. All four names below are part of the required public API.
#[doc(inline)]
pub use adler32::{adler32, adler32_combine, adler32_combine64, adler32_z};

// Re-export the complete CRC-32 surface from `crc32.c`, including the
// `*_combine*`, `*_gen*`, `*_op`, and table-accessor variants. The `*64`,
// `*_gen*`, `*_op`, and `get_crc_table` entries are consumed by `src/ffi.rs`
// even though the idiomatic `src/lib.rs` re-export uses only a subset, so the
// full set is re-exported here to satisfy every downstream consumer.
#[doc(inline)]
pub use crc32::{
    crc32, crc32_combine, crc32_combine_gen, crc32_combine_gen64, crc32_combine_op,
    crc32_combine64, crc32_z, get_crc_table,
};
