//! Checksum engine for `zlib-rs`: Adler-32 (RFC 1950) and CRC-32 (IEEE).
//!
//! Ported from zlib's `adler32.c` and `crc32.c`; both produce values that are
//! **bit-for-bit identical** to C zlib, including the `*_combine` variants that
//! back the zlib/gzip stream trailers and `strm.adler`.
//!
//! * [`adler32()`] / [`adler32_z()`] — Adler-32 (modulo 65521).
//! * [`crc32()`] / [`crc32_z()`] — CRC-32 (reflected polynomial `0xEDB88320`),
//!   slice-by-8 scalar table (generated by `build.rs`) with optional
//!   `crc32fast` SIMD acceleration under the `simd` feature.
//!
//! All scalar paths are `no_std`-clean (`core` only).
//!
//! # Why the checksums matter
//!
//! Neither algorithm performs compression, yet both are integral to the
//! container formats this crate produces and consumes:
//!
//! * The **zlib** wrapper (RFC 1950) terminates every stream with a big-endian
//!   Adler-32 of the *uncompressed* data; the running value is mirrored in the
//!   public `strm.adler` field while a stream is in flight.
//! * The **gzip** wrapper (RFC 1952) terminates every member with a
//!   little-endian CRC-32 of the *uncompressed* data followed by the input
//!   length modulo 2³².
//!
//! Because these values travel on the wire, any deviation from canonical C
//! zlib — even by a single bit — would render a stream unreadable by other
//! conformant decoders. The submodules are therefore validated bit-for-bit
//! against reference zlib, and this module simply re-exports their results.
//!
//! # Module layout
//!
//! This file is the **module root** for the checksum engine and contains no
//! algorithm logic of its own — only the submodule declarations below and the
//! flattening re-exports that follow. The two engines live in sibling files:
//!
//! * `adler32` — the Adler-32 rolling checksum (modulo `65521`, the largest
//!   prime below 2¹⁶).
//! * `crc32` — the table-driven CRC-32 plus its `crc32fast` SIMD fast path.
//!
//! A module and a same-named function occupy different namespaces, so the
//! `adler32` *module* and the re-exported `adler32` *function* (likewise for
//! `crc32`) coexist here without conflict — idiomatic, valid Rust.
//!
//! # Exported functions
//!
//! Every symbol declared in the checksum section of `zlib.h` is re-exported
//! here, so consumers refer to `crate::checksum::<name>` without reaching into
//! the submodules. The flattened surface is:
//!
//! ### Adler-32
//! * [`adler32()`] — one-shot / incremental update (`uInt` length, mirrors C
//!   `adler32`); seed with `1` to begin a fresh checksum.
//! * [`adler32_z()`] — identical to [`adler32()`] but with a `usize` length.
//! * [`adler32_combine()`] — combine the checksums of two byte sequences into
//!   the checksum of their concatenation, given only the second length.
//! * [`adler32_combine64()`] — the 64-bit-length variant of
//!   [`adler32_combine()`].
//!
//! ### CRC-32
//! * [`crc32()`] — one-shot / incremental update (`uInt` length, mirrors C
//!   `crc32`); seed with `0` to begin a fresh checksum.
//! * [`crc32_z()`] — identical to [`crc32()`] but with a `usize` length.
//! * [`crc32_combine()`] — combine two CRC-32 values into the value of their
//!   concatenation, given only the second length.
//! * [`crc32_combine64()`] — the 64-bit-length variant of [`crc32_combine()`].
//! * [`crc32_combine_gen()`] — precompute the combine *operator* for a length,
//!   amortizing repeated combines at that length.
//! * [`crc32_combine_gen64()`] — the 64-bit-length variant of
//!   [`crc32_combine_gen()`].
//! * [`crc32_combine_op()`] — combine two CRC-32 values using a precomputed
//!   operator from [`crc32_combine_gen()`].
//! * [`get_crc_table()`] — borrow the 256-entry CRC-32 lookup table (mirrors C
//!   `get_crc_table`, primarily for FFI parity).
//!
//! # Features and `no_std`
//!
//! This module is entirely **feature-agnostic**: it contains no `cfg`-gated
//! code and compiles unchanged under every supported feature combination
//! (`default`, `std`-only, `no-std`, and `simd`). All feature behavior is
//! localized to the submodules:
//!
//! * With the `simd` feature (on by default), [`crc32()`] delegates to the
//!   `crc32fast` crate's SIMD-accelerated engine; without it, the portable
//!   slice-by-8 scalar table (generated by `build.rs`) is used. Both engines
//!   compute the identical IEEE CRC-32.
//! * Every scalar path uses only [`core`], performs no heap allocation, and
//!   contains **zero `unsafe`**, so the engine builds for the `no-std`
//!   (`Z_SOLO`-equivalent) target without modification.
//!
//! # Consumers
//!
//! The re-export roster is the union of what the crate's public surface needs:
//! `crate::lib` lifts the common six ([`adler32()`], [`adler32_z()`],
//! [`adler32_combine()`], [`crc32()`], [`crc32_z()`], [`crc32_combine()`]) into
//! the crate root, while the `extern "C"` FFI shim additionally binds the
//! 64-bit-length, combine-operator, and table-accessor entry points to their
//! exact C symbol names. Keeping the full set re-exported here means a single
//! import path (`crate::checksum::<name>`) resolves for both.

pub mod adler32;
pub mod crc32;

// Adler-32 (RFC 1950) public surface — the rolling checksum used by the zlib
// stream trailer and tracked in `strm.adler`.
#[doc(inline)]
pub use adler32::{adler32, adler32_combine, adler32_combine64, adler32_z};

// CRC-32 (IEEE 802.3 / RFC 1952) public surface — the checksum used by the
// gzip member trailer, plus the combine and table-accessor helpers required
// for full C-API parity.
#[doc(inline)]
pub use crc32::{
    crc32, crc32_combine, crc32_combine_gen, crc32_combine_gen64, crc32_combine_op,
    crc32_combine64, crc32_z, get_crc_table,
};
